import type { Config } from 'tailwindcss'
import { fontFamily } from 'tailwindcss/defaultTheme'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'var(--font-geist-sans)', ...fontFamily.sans],
        mono: ['Fira Code', 'var(--font-geist-mono)', ...fontFamily.mono],
        display: ['var(--font-display)', ...fontFamily.serif],
      },
      colors: {
        // Primary Brand - Indigo (Purple)
        primary: {
          50: '#F5F3FF',
          100: '#EDE9FE',
          200: '#DDD6FE',
          300: '#C4B5FD',
          400: '#A78BFA',
          500: '#8B5CF6',
          600: '#5B4FD8',
          700: '#4939C0',
          800: '#3D2FA8',
          900: '#312E81',
        },
        // Brand (keep for backwards compatibility)
        brand: {
          50: '#f0f4ff',
          100: '#e0eaff',
          200: '#c7d7fe',
          300: '#a5b8fc',
          400: '#8191f8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b',
        },
        // Surface colors - Theme-responsive using CSS variables
        surface: {
          0: 'rgb(var(--surface-0) / <alpha-value>)',
          50: 'rgb(var(--surface-50) / <alpha-value>)',
          100: 'rgb(var(--surface-100) / <alpha-value>)',
          200: 'rgb(var(--surface-200) / <alpha-value>)',
          300: 'rgb(var(--surface-300) / <alpha-value>)',
          400: 'rgb(var(--surface-400) / <alpha-value>)',
          500: 'rgb(var(--surface-500) / <alpha-value>)',
          600: 'rgb(var(--surface-600) / <alpha-value>)',
          700: 'rgb(var(--surface-700) / <alpha-value>)',
          800: 'rgb(var(--surface-800) / <alpha-value>)',
          900: 'rgb(var(--surface-900) / <alpha-value>)',
          950: 'rgb(var(--surface-950) / <alpha-value>)',
        },
        // Semantic colors
        success: {
          50: '#ECFDF5',
          100: '#D1FAE5',
          200: '#A7F3D0',
          500: '#10B981',
          600: '#059669',
          700: '#047857',
        },
        warning: {
          50: '#FFFBEB',
          100: '#FEF3C7',
          200: '#FDE68A',
          500: '#F59E0B',
          600: '#D97706',
          700: '#B45309',
        },
        error: {
          50: '#FEF2F2',
          100: '#FEE2E2',
          200: '#FECACA',
          500: '#F56565',
          600: '#E53E3E',
          700: '#C53030',
        },
        info: {
          50: '#EFF6FF',
          100: '#DBEAFE',
          200: '#BFDBFE',
          500: '#4299E1',
          600: '#3182CE',
          700: '#2B6CB0',
        },
        // UI colors
        card: {
          DEFAULT: 'rgb(var(--color-card) / <alpha-value>)',
          hover: 'rgb(var(--color-card-hover) / <alpha-value>)',
        },
        'app-sidebar': 'rgb(var(--color-sidebar) / <alpha-value>)',
        'app-topbar': 'rgb(var(--color-topbar) / <alpha-value>)',
        'app-input': 'rgb(var(--color-input) / <alpha-value>)',
        'app-input-border': 'rgb(var(--color-input-border) / <alpha-value>)',
        'app-tooltip-bg': 'rgb(var(--color-tooltip-bg) / <alpha-value>)',
        'app-tooltip-border': 'rgb(var(--color-tooltip-border) / <alpha-value>)',
        'app-badge-bg': 'rgb(var(--color-badge-bg) / <alpha-value>)',
        'app-code-bg': 'rgb(var(--color-code-bg) / <alpha-value>)',
        // Page backgrounds
        'page-bg': 'rgb(var(--color-page-bg) / <alpha-value>)',
        'page-bg-alt': 'rgb(var(--color-page-bg-alt) / <alpha-value>)',
        'page-bg-elevated': 'rgb(var(--color-page-bg-elevated) / <alpha-value>)',
        // Auth-specific
        'auth-card': 'rgb(var(--color-auth-card) / <alpha-value>)',
        'auth-input': 'rgb(var(--color-auth-input) / <alpha-value>)',
        'auth-input-border': 'rgb(var(--color-auth-input-border) / <alpha-value>)',
        'auth-label': 'rgb(var(--color-auth-label) / <alpha-value>)',
        'auth-muted': 'rgb(var(--color-auth-muted) / <alpha-value>)',
        'auth-input-text': 'rgb(var(--color-auth-input-text) / <alpha-value>)',
        // Nav surfaces
        'nav-bg': 'rgb(var(--color-nav-bg) / <alpha-value>)',
        'nav-border': 'rgb(var(--color-nav-border) / <alpha-value>)',
        'nav-text': 'rgb(var(--color-nav-text) / <alpha-value>)',
        'nav-text-hover': 'rgb(var(--color-nav-text-hover) / <alpha-value>)',
        'nav-text-active': 'rgb(var(--color-nav-text-active) / <alpha-value>)',
        'nav-active-bg': 'rgb(var(--color-nav-active-bg) / <alpha-value>)',
        'nav-active-text': 'rgb(var(--color-nav-active-text) / <alpha-value>)',
        // Search
        'search-bg': 'rgb(var(--color-search-bg) / <alpha-value>)',
        'search-border': 'rgb(var(--color-search-border) / <alpha-value>)',
        'search-text': 'rgb(var(--color-search-text) / <alpha-value>)',
        'search-placeholder': 'rgb(var(--color-search-placeholder) / <alpha-value>)',
        // Extended surfaces
        'surface-input': 'rgb(var(--color-surface-input) / <alpha-value>)',
        'surface-input-border': 'rgb(var(--color-surface-input-border) / <alpha-value>)',
        'surface-row': 'rgb(var(--color-surface-row) / <alpha-value>)',
        'surface-row-hover': 'rgb(var(--color-surface-row-hover) / <alpha-value>)',
        'text-on-surface': 'rgb(var(--color-text-on-surface) / <alpha-value>)',
        'text-secondary-surface': 'rgb(var(--color-text-secondary-on-surface) / <alpha-value>)',
        'text-muted-surface': 'rgb(var(--color-text-muted-on-surface) / <alpha-value>)',
        // Dashboard dark surfaces
        'dashboard-bg': 'rgb(var(--color-dashboard-bg) / <alpha-value>)',
        'dashboard-card': 'rgb(var(--color-dashboard-card) / <alpha-value>)',
        'dashboard-border': 'rgb(var(--color-dashboard-border) / <alpha-value>)',
        'dashboard-text': 'rgb(var(--color-dashboard-text) / <alpha-value>)',
        'dashboard-text-muted': 'rgb(var(--color-dashboard-text-muted) / <alpha-value>)',
        'dashboard-input-bg': 'rgb(var(--color-dashboard-input-bg) / <alpha-value>)',
        'dashboard-input-border': 'rgb(var(--color-dashboard-input-border) / <alpha-value>)',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '32px',
        '3xl': '48px',
        '4xl': '64px',
      },
      borderRadius: {
        sm: '4px',
        md: '6px',
        lg: '8px',
        xl: '12px',
        '2xl': '2rem',
        '3xl': '2.5rem',
        pill: '999px',
      },
      fontSize: {
        xs: ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        sm: ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        base: ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        lg: ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        xl: ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        '2xl': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        '3xl': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        '4xl': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'grid-pattern':
          "url(\"data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%236366f1' fill-opacity='0.05'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E\")",
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'fade-up': 'fadeUp 0.5s ease-out',
        'slide-in-left': 'slideInLeft 0.4s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'spin-slow': 'spin 8s linear infinite',
        'bounce-slow': 'bounce 3s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
      boxShadow: {
        glow: '0 0 20px -5px var(--tw-shadow-color)',
        'glow-lg': '0 0 40px -10px var(--tw-shadow-color)',
        'inner-brand': 'inset 0 1px 0 0 rgba(99, 102, 241, 0.1)',
        card: 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
        sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        md: '0 2px 8px 0 rgba(0, 0, 0, 0.1)',
        lg: '0 4px 16px 0 rgba(0, 0, 0, 0.15)',
        xl: '0 8px 24px 0 rgba(0, 0, 0, 0.2)',
      },
    },
  },
  plugins: [],
}

export default config
