import type { SiteAuditResult, FixBrief, FixBriefItem } from './types'

const EFFORT_MAP: Record<string, FixBriefItem['estimatedEffort']> = {
  'Add a <title>': '5min',
  'Add a meta description': '5min',
  'Add exactly one H1': '5min',
  'Add a <link rel="canonical"': '5min',
  'Add og:title': '10min',
  'Add hreflang': '15min',
  'Add JSON-LD structured data': '30min',
  'Add FAQPage schema': '30min',
  'Add HowTo schema': '30min',
  'Write clear, concise answers': '15min',
  'Use definitive language': '15min',
  'Add clear author attribution': '15min',
  'Link to an About page': '5min',
  'Add clear contact information': '10min',
  'Cite authoritative sources': '30min',
  'Migrate to HTTPS': '2h',
  'Add a privacy policy': '1h',
  'Remove noindex': '5min',
  'Add <meta name="viewport"': '5min',
  'Add lang attribute': '5min',
  'Add descriptive alt text': '15min',
  'Add a favicon': '10min',
  'Add datePublished': '10min',
  'Add dateModified': '10min',
  'Update with current information': '1h',
  'Use <time datetime': '10min',
}

export function generateFixBrief(audit: SiteAuditResult): FixBrief {
  const failingChecks = audit.checks.filter((c) => c.status === 'fail' || c.status === 'warn')

  const items: FixBriefItem[] = failingChecks
    .sort((a, b) => {
      const priorityOrder = { critical: 0, high: 1, medium: 2, low: 3 }
      const pa = priorityOrder[a.priority]
      const pb = priorityOrder[b.priority]
      if (pa !== pb) return pa - pb
      return b.impact - a.impact
    })
    .map((check, index) => ({
      id: `fix-${index + 1}`,
      checkId: check.id,
      category: check.category.toUpperCase(),
      title: check.name,
      description: check.description,
      fix: check.fix || 'Review and fix this issue',
      priority: check.priority,
      impact: check.impact,
      estimatedEffort: getEstimatedEffort(check.fix || ''),
    }))

  return {
    siteUrl: audit.url,
    generatedAt: new Date().toISOString(),
    overallScore: audit.overallScore,
    totalIssues: items.length,
    criticalCount: items.filter((i) => i.priority === 'critical').length,
    highCount: items.filter((i) => i.priority === 'high').length,
    mediumCount: items.filter((i) => i.priority === 'medium').length,
    lowCount: items.filter((i) => i.priority === 'low').length,
    items,
  }
}

export function formatFixBriefAsMarkdown(brief: FixBrief): string {
  const lines: string[] = []

  lines.push(`# SEO/AEO/E-E-A-T Fix Brief`)
  lines.push('')
  lines.push(`**Site:** ${brief.siteUrl}`)
  lines.push(`**Generated:** ${new Date(brief.generatedAt).toLocaleDateString()}`)
  lines.push(`**Overall Score:** ${brief.overallScore}/10`)
  lines.push(
    `**Total Issues:** ${brief.totalIssues} (${brief.criticalCount} critical, ${brief.highCount} high, ${brief.mediumCount} medium, ${brief.lowCount} low)`,
  )
  lines.push('')
  lines.push('---')
  lines.push('')

  for (const item of brief.items) {
    const priorityEmoji =
      item.priority === 'critical'
        ? '🔴'
        : item.priority === 'high'
          ? '🟠'
          : item.priority === 'medium'
            ? '🟡'
            : '🟢'

    lines.push(`## ${priorityEmoji} ${item.id}: ${item.title}`)
    lines.push('')
    lines.push(`**Category:** ${item.category}`)
    lines.push(`**Priority:** ${item.priority}`)
    lines.push(`**Impact:** ${item.impact}/10`)
    lines.push(`**Estimated Effort:** ${item.estimatedEffort}`)
    lines.push('')
    lines.push(`**Current State:** ${item.description}`)
    lines.push('')
    lines.push(`**Fix:** ${item.fix}`)
    lines.push('')
    lines.push('---')
    lines.push('')
  }

  lines.push('')
  lines.push('*Generated by AIO Pulse Advance - AI-Powered Brand Monitoring*')

  return lines.join('\n')
}

function getEstimatedEffort(fixText: string): FixBriefItem['estimatedEffort'] {
  for (const [keyword, effort] of Object.entries(EFFORT_MAP)) {
    if (fixText.toLowerCase().includes(keyword.toLowerCase())) {
      return effort
    }
  }
  return '30min'
}
