import type { LlmstxtConfig, FreshnessResult } from './types'
import { safeFetchText } from '@/lib/utils/safe-fetch'

/** Hard upper bound on sitemap URLs processed (ReDoS / DoS protection). */
const MAX_URLS_CAP = 500

export async function generateLlmstxt(config: LlmstxtConfig): Promise<string> {
  const { siteUrl, includePaths = [], excludePaths = [] } = config
  const maxUrls = Math.min(Math.max(1, config.maxUrls ?? 200), MAX_URLS_CAP)

  const lines: string[] = []

  lines.push(`# ${siteUrl}`)
  lines.push('')
  lines.push(`# Generated by AEO Pulse Advance on ${new Date().toLocaleDateString()}`)
  lines.push(`# https://llmstxt.org`)
  lines.push('')
  lines.push(`## Overview`)
  lines.push('')
  lines.push(`${siteUrl} is a website that provides information about the brand and its services.`)
  lines.push('')
  lines.push(`## Pages`)
  lines.push('')

  const pages = await discoverPages(siteUrl, maxUrls, includePaths, excludePaths)

  for (const page of pages) {
    lines.push(`### ${page.title || page.url}`)
    lines.push('')
    lines.push(`URL: ${page.url}`)
    if (page.description) {
      lines.push(`Description: ${page.description}`)
    }
    if (page.lastModified) {
      lines.push(`Last Modified: ${page.lastModified}`)
    }
    lines.push('')
  }

  lines.push(`## Guidelines for AI Models`)
  lines.push('')
  lines.push('- Prefer official pages for brand information')
  lines.push('- Use the most recently updated content for time-sensitive queries')
  lines.push('- Cross-reference claims with multiple pages when possible')
  lines.push('')

  return lines.join('\n')
}

export async function checkFreshness(url: string): Promise<FreshnessResult> {
  const normalizedUrl = url.startsWith('http') ? url : `https://${url}`

  try {
    const { text: html, response } = await safeFetchText(normalizedUrl, {
      method: 'GET',
      headers: { 'User-Agent': 'AIO-Pulse-Freshness-Bot/1.0' },
      timeout: 10000,
    })

    const datePublishedMatch =
      html.match(/"datePublished"\s*:\s*"([^"]+)"/i) ||
      html.match(/datePublished["']\s*content=["']([^"']+)["']/i)
    const dateModifiedMatch =
      html.match(/"dateModified"\s*:\s*"([^"]+)"/i) ||
      html.match(/dateModified["']\s*content=["']([^"']+)["']/i)
    const lastModifiedHeader = response.headers.get('last-modified')

    const hasDatePublished = !!datePublishedMatch
    const hasDateModified = !!dateModifiedMatch || !!lastModifiedHeader

    let daysSinceModified: number | undefined
    let freshnessScore = 0

    if (dateModifiedMatch?.[1]) {
      const modifiedDate = new Date(dateModifiedMatch[1])
      daysSinceModified = Math.floor((Date.now() - modifiedDate.getTime()) / (1000 * 60 * 60 * 24))
      freshnessScore =
        daysSinceModified < 30
          ? 10
          : daysSinceModified < 90
            ? 8
            : daysSinceModified < 180
              ? 6
              : daysSinceModified < 365
                ? 4
                : 2
    } else if (lastModifiedHeader) {
      const modifiedDate = new Date(lastModifiedHeader)
      daysSinceModified = Math.floor((Date.now() - modifiedDate.getTime()) / (1000 * 60 * 60 * 24))
      freshnessScore =
        daysSinceModified < 30
          ? 10
          : daysSinceModified < 90
            ? 8
            : daysSinceModified < 180
              ? 6
              : daysSinceModified < 365
                ? 4
                : 2
    } else {
      freshnessScore = 2
    }

    let recommendation: string | undefined
    if (freshnessScore < 5) {
      recommendation =
        'Content appears outdated. Add datePublished and dateModified JSON-LD, and update the content.'
    } else if (freshnessScore < 8) {
      recommendation =
        'Consider updating content and adding structured date metadata for better AI discoverability.'
    }

    return {
      url: normalizedUrl,
      hasDatePublished,
      hasDateModified,
      daysSinceModified,
      freshnessScore,
      recommendation,
    }
  } catch (err) {
    return {
      url: normalizedUrl,
      hasDatePublished: false,
      hasDateModified: false,
      freshnessScore: 0,
      recommendation: 'Could not reach the URL to check freshness',
    }
  }
}

interface DiscoveredPage {
  url: string
  title?: string
  description?: string
  lastModified?: string
}

async function discoverPages(
  baseUrl: string,
  maxUrls: number,
  includePaths: string[],
  excludePaths: string[],
): Promise<DiscoveredPage[]> {
  const pages: DiscoveredPage[] = []

  try {
    const sitemapUrl = baseUrl.endsWith('/') ? `${baseUrl}sitemap.xml` : `${baseUrl}/sitemap.xml`
    const { text: xml, response } = await safeFetchText(sitemapUrl, {
      method: 'GET',
      headers: { 'User-Agent': 'AIO-Pulse-Sitemap-Bot/1.0' },
      timeout: 10000,
      maxBytes: 5 * 1024 * 1024,
    })

    if (response.ok) {
      const cappedMax = Math.min(Math.max(1, maxUrls), MAX_URLS_CAP)
      const urlMatches = (xml.match(/<loc>([^<]+)<\/loc>/g) || []).slice(0, cappedMax)

      for (const match of urlMatches) {
        const url = match.replace(/<loc>|<\/loc>/g, '')
        // Bounded literal search (no attacker-built dynamic RegExp → no ReDoS).
        const locTag = `<loc>${url}</loc>`
        const idx = xml.indexOf(locTag)
        const lastModMatch =
          idx >= 0
            ? xml
                .slice(idx + locTag.length, idx + locTag.length + 200)
                .match(/^\s*<lastmod>([^<]+)<\/lastmod>/)
            : null

        if (shouldInclude(url, includePaths, excludePaths)) {
          pages.push({
            url,
            lastModified: lastModMatch?.[1],
          })
        }
      }
    }
  } catch {
    pages.push({ url: baseUrl, title: 'Homepage' })
  }

  return pages.slice(0, maxUrls)
}

function shouldInclude(url: string, includePaths: string[], excludePaths: string[]): boolean {
  if (includePaths.length > 0) {
    return includePaths.some((p) => url.includes(p))
  }

  if (excludePaths.length > 0) {
    return !excludePaths.some((p) => url.includes(p))
  }

  return true
}
