import { type NextRequest, NextResponse } from 'next/server'
import { createServerClient, getCurrentUserId, AuthError } from '@/lib/supabase'
import { verifyBrandAccess } from '@/lib/authorize'
import { checkRateLimit, getClientIp } from '@/lib/ratelimit'
import { logger } from '@/lib/logger'
import { geoMethodologyNote } from '@/lib/geo-config'
import {
  calculateAVIFromResults,
  calculateDomainSOAIV,
  calculateCompetitorAVI,
  buildSentimentHeatmap,
  type DomainSOAIVResult,
  type SentimentHeatmap,
  type CompetitorGapResult,
} from '@/lib/services/monitoring'

const VALID_LOCALES = ['en', 'it', 'sv'] as const
type Locale = (typeof VALID_LOCALES)[number]

/** HTML-escape an untrusted value before interpolating into the report markup. */
function esc(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

const i18n = {
  en: {
    title: 'AI Voice Report',
    brand: 'Brand',
    period: 'Report Period',
    aviScore: 'AVI Score',
    aviHero: 'Brand Visibility Score',
    soaiv: 'Share of AI Voice (Domain)',
    domain: 'Domain',
    brandShare: 'Brand',
    competitorShare: 'Competitor',
    otherShare: 'Other',
    competitors: 'Competitor Analysis',
    rank: 'Rank',
    gap: 'Gap',
    weakPoint: 'Weakest Component',
    noData: 'No data available',
    generated: 'Generated by',
    sentiment: 'Sentiment Heatmap',
    engine: 'Engine',
    category: 'Category',
    sentimentScore: 'Sentiment',
    mentions: 'Mentions',
    components: 'AVI Components',
    citationRate: 'Citation Rate',
    mentionFrequency: 'Mention Frequency',
    sentimentScoreLabel: 'Sentiment Score',
    recommendationRate: 'Recommendation Rate',
    positionAvg: 'Position Average',
    hallucinationIndex: 'Hallucination Index',
    rank1: 'Leader',
    rank2: 'Close',
    rank3: 'Behind',
  },
  it: {
    title: 'Rapporto AI Voice',
    brand: 'Marca',
    period: 'Periodo Report',
    aviScore: 'Punteggio AVI',
    aviHero: 'Punteggio Visibilità Marca',
    soaiv: 'Share of AI Voice (Dominio)',
    domain: 'Dominio',
    brandShare: 'Marca',
    competitorShare: 'Competitor',
    otherShare: 'Altro',
    competitors: 'Analisi Competitor',
    rank: 'Rank',
    gap: 'Gap',
    weakPoint: 'Componente Più Debole',
    noData: 'Nessun dato disponibile',
    generated: 'Generato da',
    sentiment: 'Mappa Sentiment',
    engine: 'Motore',
    category: 'Categoria',
    sentimentScore: 'Sentiment',
    mentions: 'Menzioni',
    components: 'Componenti AVI',
    citationRate: 'Tasso Citazione',
    mentionFrequency: 'Frequenza Menzioni',
    sentimentScoreLabel: 'Punteggio Sentiment',
    recommendationRate: 'Tasso Raccomandazione',
    positionAvg: 'Posizione Media',
    hallucinationIndex: 'Indice Allucinazione',
    rank1: 'Leader',
    rank2: 'Vicino',
    rank3: 'Dietro',
  },
  sv: {
    title: 'AI Voice Rapport',
    brand: 'Varumärke',
    period: 'Rapportperiod',
    aviScore: 'AVI Poäng',
    aviHero: 'Varumärkets Synlighets Poäng',
    soaiv: 'Share of AI Voice (Domän)',
    domain: 'Domän',
    brandShare: 'Varumärke',
    competitorShare: 'Konkurrent',
    otherShare: 'Övrigt',
    competitors: 'Konkurrentanalys',
    rank: 'Rank',
    gap: 'Gap',
    weakPoint: 'Svagaste Komponent',
    noData: 'Ingen data tillgänglig',
    generated: 'Genererat av',
    sentiment: 'Sentiment Heatmap',
    engine: 'Motor',
    category: 'Kategori',
    sentimentScore: 'Sentiment',
    mentions: 'Omnämnanden',
    components: 'AVI Komponenter',
    citationRate: 'Citeringsfrekvens',
    mentionFrequency: 'Omnämningsfrekvens',
    sentimentScoreLabel: 'Sentiment Poäng',
    recommendationRate: 'Rekommendationsfrekvens',
    positionAvg: 'Genomsnittlig Position',
    hallucinationIndex: 'Hallucinerings Index',
    rank1: 'Ledare',
    rank2: 'Nära',
    rank3: 'Bakom',
  },
} as const

function getLabels(locale: Locale) {
  return i18n[locale] ?? i18n.en
}

function generateHtmlReport(
  brandName: string,
  fromDate: string,
  toDate: string,
  avi: number,
  components: Record<string, number>,
  soaiv: DomainSOAIVResult[],
  competitors: Array<{ name: string; rank: number; gap: number; weakestComponent: string }>,
  heatmap: SentimentHeatmap,
  locale: Locale,
): string {
  const t = getLabels(locale)
  const brandColor = '#6366f1'
  const bgColor = '#f8fafc'
  const textColor = '#1e293b'
  const mutedColor = '#64748b'

  let soaivHtml = ''
  if (soaiv.length > 0) {
    soaivHtml = `
      <h2>${t.soaiv}</h2>
      <table>
        <thead>
          <tr>
            <th>${t.domain}</th>
            <th>${t.brandShare}%</th>
            <th>${t.competitorShare}%</th>
            <th>${t.otherShare}%</th>
          </tr>
        </thead>
        <tbody>
          ${soaiv
            .map(
              (s) => `
            <tr>
              <td>${esc(s.domain)}</td>
              <td>${s.brandShare.toFixed(1)}</td>
              <td>${s.competitorShare.toFixed(1)}</td>
              <td>${s.otherShare.toFixed(1)}</td>
            </tr>
          `,
            )
            .join('')}
        </tbody>
      </table>
    `
  }

  let competitorHtml = ''
  if (competitors.length > 0) {
    competitorHtml = `
      <h2>${t.competitors}</h2>
      <table>
        <thead>
          <tr>
            <th>${t.competitorShare}</th>
            <th>${t.rank}</th>
            <th>${t.gap}</th>
            <th>${t.weakPoint}</th>
          </tr>
        </thead>
        <tbody>
          ${competitors
            .map(
              (c) => `
            <tr>
              <td>${esc(c.name)}</td>
              <td>${c.rank === 1 ? t.rank1 : c.rank === 2 ? t.rank2 : t.rank3}</td>
              <td>${c.gap > 0 ? '-' + c.gap.toFixed(1) : '+' + Math.abs(c.gap).toFixed(1)}</td>
              <td>${esc(c.weakestComponent)}</td>
            </tr>
          `,
            )
            .join('')}
        </tbody>
      </table>
    `
  }

  let heatmapHtml = ''
  if (Object.keys(heatmap).length > 0) {
    const engines = Object.keys(heatmap)
    const categories = new Set<string>()
    engines.forEach((e) => {
      const row = heatmap[e]
      if (row) Object.keys(row).forEach((c) => categories.add(c))
    })
    const categoryArr = Array.from(categories)

    heatmapHtml = `
      <h2>${t.sentiment}</h2>
      <table>
        <thead>
          <tr>
            <th>${t.engine}</th>
            ${categoryArr.map((c) => `<th>${esc(c)}</th>`).join('')}
          </tr>
        </thead>
        <tbody>
          ${engines
            .map(
              (e) => `
            <tr>
              <td>${esc(e)}</td>
              ${categoryArr
                .map((c) => {
                  const cell = heatmap[e]?.[c]
                  if (cell) {
                    return `<td>${cell.sentiment.toFixed(2)} (${cell.mentions})</td>`
                  }
                  return '<td>-</td>'
                })
                .join('')}
            </tr>
          `,
            )
            .join('')}
        </tbody>
      </table>
    `
  }

  const componentLabels: Record<string, string> = {
    citationRate: t.citationRate,
    mentionFrequency: t.mentionFrequency,
    sentimentScore: t.sentimentScoreLabel,
    recommendationRate: t.recommendationRate,
    positionAvg: t.positionAvg,
    hallucinationIndex: t.hallucinationIndex,
  }

  return `<!DOCTYPE html>
<html lang="${locale}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(brandName)} - ${t.title}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background: ${bgColor}; color: ${textColor}; line-height: 1.6; padding: 20px; }
    .container { max-width: 900px; margin: 0 auto; }
    .header { background: ${brandColor}; color: white; padding: 30px; border-radius: 8px 8px 0 0; }
    .header h1 { font-size: 28px; margin-bottom: 8px; }
    .header .subtitle { opacity: 0.9; font-size: 14px; }
    .section { background: white; padding: 24px 30px; border-left: 1px solid #e2e8f0; border-right: 1px solid #e2e8f0; }
    .section:last-of-type { border-bottom: 1px solid #e2e8f0; }
    .section h2 { font-size: 18px; margin-bottom: 16px; color: ${brandColor}; }
    .hero-avi { background: linear-gradient(135deg, ${brandColor} 0%, #818cf8 100%); color: white; padding: 40px 30px; text-align: center; }
    .hero-avi .score { font-size: 72px; font-weight: 700; line-height: 1; }
    .hero-avi .label { font-size: 16px; opacity: 0.9; margin-top: 8px; }
    .hero-avi .desc { font-size: 14px; opacity: 0.7; margin-top: 4px; }
    .components-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 16px; margin-top: 16px; }
    .component-item { background: #f1f5f9; padding: 16px; border-radius: 8px; text-align: center; }
    .component-item .value { font-size: 24px; font-weight: 600; color: ${brandColor}; }
    .component-item .name { font-size: 12px; color: ${mutedColor}; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 14px; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }
    th { background: #f8fafc; font-weight: 600; color: ${mutedColor}; }
    td { color: ${textColor}; }
    tr:last-child td { border-bottom: none; }
    .footer { padding: 20px 30px; background: #f8fafc; color: ${mutedColor}; font-size: 12px; border-radius: 0 0 8px 8px; border-left: 1px solid #e2e8f0; border-right: 1px solid #e2e8f0; border-bottom: 1px solid #e2e8f0; }
    .no-data { color: ${mutedColor}; font-style: italic; }
    @media print { body { padding: 0; } .container { max-width: 100%; } }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>${esc(brandName)}</h1>
      <div class="subtitle">${t.title} | ${t.period}: ${esc(fromDate)} - ${esc(toDate)}</div>
    </div>

    <div class="hero-avi">
      <div class="score">${avi.toFixed(1)}</div>
      <div class="label">${t.aviScore}</div>
      <div class="desc">${t.aviHero}</div>
    </div>

    <div class="section">
      <h2>${t.components}</h2>
      <div class="components-grid">
        ${Object.entries(components)
          .map(
            ([key, val]) => `
          <div class="component-item">
            <div class="value">${typeof val === 'number' ? val.toFixed(1) : esc(val)}</div>
            <div class="name">${esc(componentLabels[key] || key)}</div>
          </div>
        `,
          )
          .join('')}
      </div>
    </div>

    ${soaiv.length > 0 ? `<div class="section">${soaivHtml}</div>` : ''}

    ${competitors.length > 0 ? `<div class="section">${competitorHtml}</div>` : ''}

    ${Object.keys(heatmap).length > 0 ? `<div class="section">${heatmapHtml}</div>` : ''}

    <div class="section">
      <h2>${locale === 'it' ? 'Metodologia e Limitazioni' : locale === 'sv' ? 'Metodik och Begränsningar' : 'Methodology & Limitations'}</h2>
      <p style="font-size:13px;color:${mutedColor};line-height:1.6">${esc(geoMethodologyNote(locale))}</p>
    </div>

    <div class="footer">
      ${t.generated} AIO Pulse | ${new Date().toISOString().split('T')[0]}
    </div>
  </div>
</body>
</html>`
}

export async function GET(req: NextRequest) {
  let userId: string
  try {
    userId = await getCurrentUserId(req.headers.get('authorization'), req.headers.get('cookie'))
  } catch (e) {
    if (e instanceof AuthError)
      return NextResponse.json({ success: false, message: e.message }, { status: 401 })
    return NextResponse.json({ success: false, message: 'Authentication failed' })
  }

  const ip = getClientIp(req.headers)
  const rateCheck = await checkRateLimit(`html-report:${ip}`, 10, 60_000)
  if (!rateCheck.success) {
    return NextResponse.json(
      { success: false, message: 'Rate limit exceeded. Try again later.' },
      {
        status: 429,
        headers: { 'Retry-After': String(Math.ceil((rateCheck.resetAt - Date.now()) / 1000)) },
      },
    )
  }

  const { searchParams } = new URL(req.url)
  const brandId = searchParams.get('brandId')
  const localeParam = searchParams.get('locale') || 'en'
  const download = searchParams.get('download') === '1'
  const days = parseInt(searchParams.get('days') || '30', 10)

  const locale = VALID_LOCALES.includes(localeParam as Locale) ? (localeParam as Locale) : 'en'

  if (!brandId) {
    return NextResponse.json({ success: false, message: 'brandId is required' }, { status: 400 })
  }

  const db = createServerClient()
  if (!db) {
    return NextResponse.json(
      { success: false, message: 'Database not configured' },
      { status: 503 },
    )
  }

  const brand = await verifyBrandAccess(brandId, userId, true)
  if (!brand) {
    return NextResponse.json(
      { success: false, message: 'Brand not found or access denied' },
      { status: 404 },
    )
  }

  const brandName = brand.name || 'Brand'
  const brandDomain = brand.domain ?? null
  const brandCompetitors = brand.competitors ?? []

  const fromDate =
    new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString().split('T')[0] ?? ''
  const toDate = new Date().toISOString().split('T')[0] ?? ''

  const { data: results, error: resultsError } = await db
    .from('monitoring_results')
    .select('*, prompt:prompts(category)')
    .eq('brand_id', brandId)
    .gte('created_at', fromDate)
    .lte('created_at', toDate + 'T23:59:59')
    .order('created_at', { ascending: false })

  if (resultsError) {
    logger.error('Failed to fetch monitoring results for HTML', {
      error: resultsError.message,
      brandId,
    })
    return NextResponse.json({ success: false, message: resultsError.message }, { status: 500 })
  }

  const mappedResults = (results || []).map((r: any) => ({
    engine: r.engine,
    brand_mentioned: r.brand_mentioned ?? false,
    visibility_score: r.visibility_score ?? 0,
    sentiment_score: r.sentiment_score,
    cited_urls: r.cited_urls || [],
    has_hallucination: r.has_hallucination ?? false,
    mention_position: r.mention_position,
    category: r.prompt?.category,
  }))

  const { avi, components } = calculateAVIFromResults(mappedResults)

  const soaivResults =
    mappedResults.length > 0 && brandDomain
      ? calculateDomainSOAIV(
          mappedResults.flatMap((r: any) => r.cited_urls || []),
          brandDomain,
          brandCompetitors,
        )
      : []

  const competitorAnalysis = brandCompetitors.map((compName: string) => {
    const compMentions = mappedResults
      .flatMap((r: any) => r.competitor_mentions || [])
      .filter((m: any) => m.name === compName)
    const result: CompetitorGapResult = calculateCompetitorAVI(
      compMentions.length > 0 ? compMentions : [{ name: compName, position: 0, count: 0 }],
      avi,
    )
    return {
      name: compName,
      rank: result.rank,
      gap: avi - result.competitorAvi,
      weakestComponent: result.weakestComponent,
    }
  })

  const heatmap = buildSentimentHeatmap(mappedResults)

  const html = generateHtmlReport(
    brandName,
    fromDate,
    toDate,
    avi,
    components as unknown as Record<string, number>,
    soaivResults,
    competitorAnalysis,
    heatmap,
    locale,
  )

  const headers: Record<string, string> = {
    'Content-Type': 'text/html; charset=utf-8',
  }

  if (download) {
    const safeName =
      String(brandName)
        .replace(/[^a-zA-Z0-9_-]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .slice(0, 60) || 'report'
    headers['Content-Disposition'] =
      `attachment; filename="${safeName}-report-${fromDate}-${toDate}.html"`
  }

  return new NextResponse(html, { headers })
}
