// PATH: src/app/api/reports/html/route.ts
//
// The full brand report. This is the one artifact a customer forwards to
// their boss, and it used to show four sections while the dashboards computed
// a dozen — the report was the weakest surface in the product precisely where
// the product gets judged from outside.
//
// Sections, in order: executive tiles → per-engine breakdown → GEO pillars →
// trend → cited domains with authority categories → sentiment → share of
// voice → keywords → site audit (only when one has been run) →
// recommendations → every prompt with its latest answers → methodology.
//
// Sections render only when their data exists. A section built on three rows
// or an audit that never ran is omitted, not padded — a missing section is
// recoverable, a confidently thin one is what this rewrite replaces.

import { type NextRequest, NextResponse } from 'next/server'
import { createServerClient, getCurrentUserId, AuthError } from '@/lib/supabase'
import { verifyBrandAccess } from '@/lib/authorize'
import { checkRateLimit, getClientIp } from '@/lib/ratelimit'
import { logger } from '@/lib/logger'
import { geoMethodologyNote } from '@/lib/geo-config'
import { calculateGeoScore, type GeoScoreInput } from '@/lib/services/geo-score'
import { computeShareOfVoice, type SovInputRow } from '@/lib/services/share-of-voice'
import { loadLatestSiteAuditSummary } from '@/lib/services/site-audit-summary'
import {
  buildEngineBreakdown,
  buildCitedDomains,
  buildPromptAnswers,
  type ReportResultRow,
} from '@/lib/services/report-sections'
import { normalizeEntityName } from '@/lib/services/competitor-identity'

const VALID_LOCALES = ['en', 'it', 'sv'] as const
type Locale = (typeof VALID_LOCALES)[number]

const ENGINE_LABEL: Record<string, string> = {
  chatgpt: 'ChatGPT',
  gemini: 'Gemini',
  perplexity: 'Perplexity',
  claude: 'Claude',
}

/** HTML-escape an untrusted value before interpolating into the report markup. */
function esc(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

const i18n = {
  en: {
    title: 'AI Visibility Report',
    period: 'Period',
    engines: 'Engines',
    preparedBy: 'Prepared by',
    summary: 'Summary',
    summaryLede: (n: number, p: number, d: number) =>
      `How the brand appears when a consumer asks an AI engine: ${n} answers collected from ${p} monitoring prompts over ${d} days.`,
    avi: 'AVI · AI visibility',
    aviSub: 'out of 100, latest day',
    geo: 'GEO Score',
    mentionRate: 'Mention rate',
    ofAnswers: (m: number, n: number) => `${m} of ${n} answers`,
    sov: 'Share of AI Voice',
    sovSub: 'of all brand mentions',
    negAnswers: 'Negative answers',
    posNeu: (p: number, n: number) => `${p} positive · ${n} neutral`,
    monitoring: 'Monitoring',
    monitoringLede:
      'Each prompt is sent to the engines; each answer is analysed for mention, position, tone and sources.',
    engine: 'Engine',
    answers: 'Answers',
    mention: 'Mention',
    posAvg: 'Avg position¹',
    visibility: 'Visibility',
    tone: 'Tone +/○/−',
    posFootnote: '¹ Sentence where the brand is first named (1 = opening sentence).',
    insights: 'Insights',
    geoTitle: (s: number) => `GEO Score: ${s}/100`,
    geoLede:
      'How well the brand is optimised to be surfaced and cited by generative engines — a weighted blend of five pillars:',
    weight: 'weight',
    trend: 'Visibility over time (AVI)',
    date: 'Date',
    sources: 'Which sources the engines link',
    ownDomain: 'own domain',
    byCategory: 'By source type',
    sentiment: 'Tone',
    positive: 'Positive',
    neutral: 'Neutral',
    negative: 'Negative',
    competitors: 'Competitors and Share of AI Voice',
    sovLede: 'Share of all brand mentions in the period, per the AEO Pulse model:',
    discovered: (s: number) =>
      `A further ${s}% goes to actors discovered outside the configuration.`,
    notConfigured: 'not configured',
    keywords: 'Keywords in the answers',
    keywordsLede: 'The most frequent words in answers where the brand appears:',
    siteAudit: 'Site audit',
    siteAuditLede: (score: number, date: string) =>
      `Technical AI-readiness of the site, last audited ${date}. Overall: ${score}/100.`,
    checks: 'checks',
    recommendations: 'Recommendations',
    recLede: 'Prioritised by estimated effect on the GEO Score.',
    uplift: (p: number) => `+${p} pts potential`,
    pillarNow: (label: string, s: number) => `pillar “${label}”, currently ${s}/100`,
    qa: 'All prompts and answers',
    qaLede: (n: number) =>
      `All ${n} monitored prompts with the latest answer from each engine, sorted by mention rate. Click a prompt to read the full answers.`,
    runs: 'runs',
    mentioned: 'mentioned',
    notMentioned: 'not mentioned',
    sentence: 'sentence',
    method: 'Methodology',
    generated: 'Generated by',
    noData: 'No monitoring data in this period.',
  },
  it: {
    title: 'Rapporto di visibilità AI',
    period: 'Periodo',
    engines: 'Motori',
    preparedBy: 'Preparato da',
    summary: 'Sintesi',
    summaryLede: (n: number, p: number, d: number) =>
      `Come appare il brand quando un consumatore interroga un motore AI: ${n} risposte raccolte da ${p} prompt di monitoraggio in ${d} giorni.`,
    avi: 'AVI · visibilità AI',
    aviSub: 'su 100, ultimo giorno',
    geo: 'GEO Score',
    mentionRate: 'Tasso di menzione',
    ofAnswers: (m: number, n: number) => `${m} risposte su ${n}`,
    sov: 'Share of AI Voice',
    sovSub: 'di tutte le menzioni di brand',
    negAnswers: 'Risposte negative',
    posNeu: (p: number, n: number) => `${p} positive · ${n} neutre`,
    monitoring: 'Monitoraggio',
    monitoringLede:
      'Ogni prompt viene inviato ai motori; ogni risposta è analizzata per menzione, posizione, tono e fonti.',
    engine: 'Motore',
    answers: 'Risposte',
    mention: 'Menzione',
    posAvg: 'Posizione media¹',
    visibility: 'Visibilità',
    tone: 'Tono +/○/−',
    posFootnote: '¹ Frase in cui il brand compare per la prima volta (1 = frase di apertura).',
    insights: 'Insight',
    geoTitle: (s: number) => `GEO Score: ${s}/100`,
    geoLede:
      'Quanto il brand è ottimizzato per essere trovato e citato dai motori generativi — media pesata di cinque pilastri:',
    weight: 'peso',
    trend: 'Andamento della visibilità (AVI)',
    date: 'Data',
    sources: 'Le fonti che i motori linkano',
    ownDomain: 'dominio proprio',
    byCategory: 'Per tipo di fonte',
    sentiment: 'Tono',
    positive: 'Positive',
    neutral: 'Neutre',
    negative: 'Negative',
    competitors: 'Competitor e Share of AI Voice',
    sovLede: 'Quota di tutte le menzioni di brand nel periodo, secondo il modello AEO Pulse:',
    discovered: (s: number) =>
      `Un ulteriore ${s}% va ad attori scoperti fuori dalla configurazione.`,
    notConfigured: 'non configurato',
    keywords: 'Parole chiave nelle risposte',
    keywordsLede: 'Le parole più frequenti nelle risposte in cui il brand compare:',
    siteAudit: 'Audit del sito',
    siteAuditLede: (score: number, date: string) =>
      `Prontezza tecnica AI del sito, ultimo audit ${date}. Complessivo: ${score}/100.`,
    checks: 'controlli',
    recommendations: 'Raccomandazioni',
    recLede: 'In ordine di impatto stimato sul GEO Score.',
    uplift: (p: number) => `+${p} pt potenziali`,
    pillarNow: (label: string, s: number) => `pilastro «${label}», oggi ${s}/100`,
    qa: 'Tutti i prompt e le risposte',
    qaLede: (n: number) =>
      `Tutti i ${n} prompt monitorati con l'ultima risposta di ogni motore, ordinati per tasso di menzione. Clicca un prompt per leggere le risposte integrali.`,
    runs: 'esecuzioni',
    mentioned: 'menzionato',
    notMentioned: 'non menzionato',
    sentence: 'frase',
    method: 'Metodologia',
    generated: 'Generato da',
    noData: 'Nessun dato di monitoraggio nel periodo.',
  },
  sv: {
    title: 'AI-synlighetsrapport',
    period: 'Period',
    engines: 'Motorer',
    preparedBy: 'Framtagen av',
    summary: 'Sammanfattning',
    summaryLede: (n: number, p: number, d: number) =>
      `Hur varumärket framstår när en konsument frågar en AI-motor: ${n} svar insamlade från ${p} bevakningsfrågor under ${d} dagar.`,
    avi: 'AVI · AI-synlighet',
    aviSub: 'av 100, senaste dagen',
    geo: 'GEO-poäng',
    mentionRate: 'Omnämnandegrad',
    ofAnswers: (m: number, n: number) => `${m} av ${n} svar`,
    sov: 'Share of AI Voice',
    sovSub: 'av alla varumärkesomnämnanden',
    negAnswers: 'Negativa svar',
    posNeu: (p: number, n: number) => `${p} positiva · ${n} neutrala`,
    monitoring: 'Bevakning',
    monitoringLede:
      'Varje fråga skickas till motorerna; varje svar analyseras för omnämnande, position, ton och källor.',
    engine: 'Motor',
    answers: 'Svar',
    mention: 'Omnämnande',
    posAvg: 'Snittposition¹',
    visibility: 'Synlighet',
    tone: 'Ton +/○/−',
    posFootnote: '¹ Meningen där varumärket först nämns (1 = svarets första mening).',
    insights: 'Insikter',
    geoTitle: (s: number) => `GEO-poäng: ${s}/100`,
    geoLede:
      'Hur väl varumärket är optimerat för att hittas och citeras av generativa motorer — ett viktat medel av fem pelare:',
    weight: 'vikt',
    trend: 'Synlighetens utveckling (AVI)',
    date: 'Datum',
    sources: 'Vilka källor motorerna länkar',
    ownDomain: 'egen domän',
    byCategory: 'Per källtyp',
    sentiment: 'Ton',
    positive: 'Positiva',
    neutral: 'Neutrala',
    negative: 'Negativa',
    competitors: 'Konkurrenter och Share of AI Voice',
    sovLede:
      'Andel av alla varumärkesomnämnanden under perioden, enligt AEO Pulse beräkningsmodell:',
    discovered: (s: number) =>
      `Ytterligare ${s} % går till upptäckta aktörer utanför konfigurationen.`,
    notConfigured: 'ej konfigurerad',
    keywords: 'Nyckelord i svaren',
    keywordsLede: 'De vanligaste orden i svaren där varumärket förekommer:',
    siteAudit: 'Sajtgranskning',
    siteAuditLede: (score: number, date: string) =>
      `Sajtens tekniska AI-beredskap, senast granskad ${date}. Samlat: ${score}/100.`,
    checks: 'kontroller',
    recommendations: 'Rekommendationer',
    recLede: 'Prioriterat efter uppskattad effekt på GEO-poängen.',
    uplift: (p: number) => `+${p} p potential`,
    pillarNow: (label: string, s: number) => `pelaren «${label}», i dag ${s}/100`,
    qa: 'Alla frågor och svar',
    qaLede: (n: number) =>
      `Samtliga ${n} bevakningsfrågor med senaste svaret från varje motor, sorterade efter omnämnandegrad. Klicka på en fråga för att läsa svaren i sin helhet.`,
    runs: 'körningar',
    mentioned: 'nämnd',
    notMentioned: 'ej nämnd',
    sentence: 'mening',
    method: 'Metod',
    generated: 'Genererad av',
    noData: 'Ingen bevakningsdata under perioden.',
  },
} as const

/** GEO pillar labels per locale — the stored labels are English. */
const PILLAR_I18N: Record<Locale, Record<string, string>> = {
  en: {},
  it: {
    'Citation Rate': 'Citazioni',
    'Brand Presence': 'Presenza del brand',
    'Recommendation Authority': 'Autorevolezza',
    'Answer Position': 'Posizione nella risposta',
    'Trust & Accuracy': 'Fiducia e accuratezza',
  },
  sv: {
    'Citation Rate': 'Källhänvisningar',
    'Brand Presence': 'Varumärkesnärvaro',
    'Recommendation Authority': 'Rekommendationsstyrka',
    'Answer Position': 'Position i svaret',
    'Trust & Accuracy': 'Förtroende & korrekthet',
  },
}

const SOURCE_CATEGORY_I18N: Record<Locale, Record<string, string>> = {
  en: {
    commercial: 'commercial sites',
    social: 'social media',
    community: 'communities & forums',
    aggregator: 'aggregators',
    wiki: 'wiki',
    institutional: 'institutional',
    official_press: 'press',
    unknown: 'other',
  },
  it: {
    commercial: 'siti commerciali',
    social: 'social media',
    community: 'community e forum',
    aggregator: 'aggregatori',
    wiki: 'wiki',
    institutional: 'istituzionali',
    official_press: 'stampa',
    unknown: 'altro',
  },
  sv: {
    commercial: 'kommersiella sajter',
    social: 'sociala medier',
    community: 'communityn & forum',
    aggregator: 'aggregatorer',
    wiki: 'wiki',
    institutional: 'institutionella',
    official_press: 'press',
    unknown: 'övrigt',
  },
}

function bar(
  label: string,
  value: number,
  max: number,
  opts: { suffix?: string; note?: string; highlight?: boolean } = {},
): string {
  const w = max > 0 ? Math.max(2, Math.round((value / max) * 100)) : 0
  return `<div class="bar-row"><span class="bar-label">${esc(label)}${opts.note ?? ''}</span><span class="bar-track"><span class="bar-fill${opts.highlight ? ' hl' : ''}" style="width:${w}%"></span></span><span class="bar-val">${value}${opts.suffix ?? ''}</span></div>`
}

function trendSvg(points: Array<{ date: string; avi: number }>): string {
  if (points.length < 2) return ''
  const W = 720
  const H = 190
  const PL = 34
  const PR = 14
  const PT = 12
  const PB = 24
  const xs = points.map((_, i) => PL + (i * (W - PL - PR)) / (points.length - 1))
  const lo = 0
  const hi = 100
  const y = (v: number) => PT + (1 - (v - lo) / (hi - lo)) * (H - PT - PB)
  const line = points.map((p, i) => `${xs[i]!.toFixed(1)},${y(p.avi).toFixed(1)}`).join(' ')
  const grid = [0, 25, 50, 75, 100]
    .map(
      (v) =>
        `<line x1="${PL}" x2="${W - PR}" y1="${y(v)}" y2="${y(v)}" stroke="#e5e2da" stroke-width="1"/><text x="${PL - 6}" y="${y(v) + 3.5}" text-anchor="end" class="tick">${v}</text>`,
    )
    .join('')
  // Label every nth date so long windows stay legible.
  const step = Math.ceil(points.length / 12)
  const labels = points
    .map((p, i) =>
      i % step === 0 || i === points.length - 1
        ? `<text x="${xs[i]}" y="${H - 6}" text-anchor="middle" class="tick">${esc(p.date.slice(5))}</text>`
        : '',
    )
    .join('')
  const dots = points
    .map(
      (p, i) =>
        `<circle cx="${xs[i]}" cy="${y(p.avi)}" r="3.5" fill="#2a78d6"><title>${esc(p.date)}: ${p.avi}</title></circle>`,
    )
    .join('')
  return `<svg viewBox="0 0 ${W} ${H}" role="img"><rect width="${W}" height="${H}" fill="none"/>${grid}${labels}<polyline points="${line}" fill="none" stroke="#2a78d6" stroke-width="2" stroke-linejoin="round"/>${dots}</svg>`
}

export async function GET(req: NextRequest) {
  let userId: string
  try {
    userId = await getCurrentUserId(req.headers.get('authorization'), req.headers.get('cookie'))
  } catch (e) {
    if (e instanceof AuthError)
      return NextResponse.json({ success: false, message: e.message }, { status: 401 })
    return NextResponse.json({ success: false, message: 'Authentication failed' })
  }

  const ip = getClientIp(req.headers)
  const rateCheck = await checkRateLimit(`html-report:${ip}`, 10, 60_000)
  if (!rateCheck.success) {
    return NextResponse.json(
      { success: false, message: 'Rate limit exceeded. Try again later.' },
      {
        status: 429,
        headers: { 'Retry-After': String(Math.ceil((rateCheck.resetAt - Date.now()) / 1000)) },
      },
    )
  }

  const { searchParams } = new URL(req.url)
  const brandId = searchParams.get('brandId')
  const localeParam = searchParams.get('locale') || 'en'
  const download = searchParams.get('download') === '1'
  // Clamp instead of trusting parseInt: `?days=abc` → NaN → new Date(NaN)
  // .toISOString() throws a bare 500, and a negative value silently renders an
  // empty report by putting fromDate in the future.
  const daysRaw = Number(searchParams.get('days') || 30)
  const days = Number.isFinite(daysRaw) ? Math.min(365, Math.max(1, Math.trunc(daysRaw))) : 30
  /** The answers appendix doubles the document size; opt-out for embedding. */
  const includeAnswers = searchParams.get('answers') !== '0'

  const locale = VALID_LOCALES.includes(localeParam as Locale) ? (localeParam as Locale) : 'en'
  const t = i18n[locale]
  const pillarL = PILLAR_I18N[locale]
  const catL = SOURCE_CATEGORY_I18N[locale]

  if (!brandId) {
    return NextResponse.json({ success: false, message: 'brandId is required' }, { status: 400 })
  }

  const db = createServerClient()
  if (!db) {
    return NextResponse.json(
      { success: false, message: 'Database not configured' },
      { status: 503 },
    )
  }

  const brand = await verifyBrandAccess(brandId, userId, true)
  if (!brand) {
    return NextResponse.json(
      { success: false, message: 'Brand not found or access denied' },
      { status: 404 },
    )
  }

  const brandName = brand.name || 'Brand'
  const brandDomain = brand.domain ?? null
  const brandCompetitors = brand.competitors ?? []
  const brandColor = /^#[0-9a-fA-F]{6}$/.test(brand.color ?? '')
    ? (brand.color as string)
    : '#a16207'

  const fromDate = new Date(Date.now() - days * 86400000).toISOString().split('T')[0] ?? ''
  const toDate = new Date().toISOString().split('T')[0] ?? ''

  const [resultsRes, promptsRes, healthRes, keywordsRes, auditSummary] = await Promise.all([
    db
      .from('monitoring_results')
      .select('*, prompt:prompts(text, category, language)')
      .eq('brand_id', brandId)
      .gte('created_at', fromDate)
      .lte('created_at', toDate + 'T23:59:59')
      .order('created_at', { ascending: false }),
    db.from('prompts').select('id, text, category, language').eq('brand_id', brandId),
    db
      .from('brand_health_scores')
      .select('date, avi_score, mention_rate')
      .eq('brand_id', brandId)
      .gte('date', fromDate)
      .order('date', { ascending: true }),
    db
      .from('keyword_tracking')
      .select('keyword, mention_count, cluster')
      .eq('brand_id', brandId)
      .eq('is_active', true)
      .order('mention_count', { ascending: false })
      .limit(11),
    loadLatestSiteAuditSummary(brandId),
  ])

  if (resultsRes.error) {
    logger.error('Failed to fetch monitoring results for HTML report', {
      error: resultsRes.error.message,
      brandId,
    })
    return NextResponse.json({ success: false, message: resultsRes.error.message }, { status: 500 })
  }

  /* eslint-disable @typescript-eslint/no-explicit-any */
  const rows: ReportResultRow[] = (resultsRes.data || []).map((r: any) => ({
    engine: r.engine,
    brand_mentioned: r.brand_mentioned ?? false,
    mention_position: r.mention_position ?? null,
    mention_count: r.mention_count ?? null,
    visibility_score: r.visibility_score ?? 0,
    sentiment: r.sentiment ?? null,
    sentiment_score: r.sentiment_score ?? null,
    cited_urls: r.cited_urls || [],
    competitor_mentions: r.competitor_mentions || [],
    response_text: r.response_text ?? null,
    prompt_id: r.prompt_id ?? null,
    created_at: r.created_at ?? null,
  }))
  /* eslint-enable @typescript-eslint/no-explicit-any */

  const pct = (n: number, d: number) => (d ? Math.round((n / d) * 100) : 0)

  // ── aggregates ─────────────────────────────────────────────────────────────
  const engines = buildEngineBreakdown(rows)
  const shownEngines = new Set(engines.map((e) => e.engine))
  // Every downstream figure describes the same population the engine table
  // shows. Mixing dropped-engine rows into totals while hiding the engine row
  // would make the numbers quietly disagree with their own breakdown.
  const scoped = rows.filter((r) => shownEngines.has(r.engine))
  const N = scoped.length
  const mentioned = scoped.filter((r) => r.brand_mentioned).length
  // Sentiment counts only rows where the brand was actually mentioned. The
  // analyzer stores every unmentioned response as neutral ("factual or absent →
  // neutral", and the zod schema defaults to 'neutral'), so pooling all rows
  // would drown real signal in unmentioned neutrals: a 5%-mentioned brand whose
  // every mention is negative would chart as ~95% "neutral" and read as calm.
  const sent = { positive: 0, neutral: 0, negative: 0 }
  for (const r of scoped)
    if (r.brand_mentioned && r.sentiment && r.sentiment in sent)
      sent[r.sentiment as keyof typeof sent]++

  const sov = computeShareOfVoice(scoped as unknown as SovInputRow[], brandName, {
    declaredCompetitors: brandCompetitors,
    maxSeries: 6,
  })
  // Same normalisation the SoV matcher uses to decide declared-ness. A naive
  // toLowerCase() set disagrees with it whenever the engine drops a legal
  // suffix ("Björn Lundén" vs the configured "Björn Lundén AB") and the report
  // would flag the client's own declared rival as "not configured".
  const configuredKeys = new Set(brandCompetitors.map((c: string) => normalizeEntityName(c)))

  const latestHealth = (healthRes.data ?? [])[healthRes.data ? healthRes.data.length - 1 : 0]
  const geoInput: GeoScoreInput | null = latestHealth
    ? await (async () => {
        const { data: full } = await db
          .from('brand_health_scores')
          .select(
            'citation_rate, mention_rate, recommendation_rate, sentiment_score, position_avg, hallucination_rate, visibility_score',
          )
          .eq('brand_id', brandId)
          .eq('date', latestHealth.date)
          .maybeSingle()
        if (!full) return null
        return {
          citationRate: full.citation_rate ?? null,
          mentionRate: full.mention_rate ?? full.visibility_score ?? null,
          recommendationRate: full.recommendation_rate ?? null,
          sentimentScore: full.sentiment_score ?? null,
          positionAvg: full.position_avg ?? null,
          hallucinationRate: full.hallucination_rate ?? null,
        }
      })()
    : null
  const geo = geoInput ? calculateGeoScore(geoInput) : null

  const cited = buildCitedDomains(scoped, brandDomain)

  const prompts = (promptsRes.data ?? []) as Array<{
    id: string
    text: string
    category: string | null
    language: string | null
  }>
  const qa = includeAnswers ? buildPromptAnswers(scoped, prompts, [...shownEngines]) : []

  const trendPoints = (healthRes.data ?? []).map((h) => ({
    date: String(h.date),
    avi: Math.round((h.avi_score ?? 0) * 10) / 10,
  }))

  const keywords = (keywordsRes.data ?? [])
    .filter((k) => k.keyword?.toLowerCase() !== brandName.toLowerCase())
    .slice(0, 10)

  // ── sections ───────────────────────────────────────────────────────────────
  const tiles: string[] = []
  if (trendPoints.length)
    tiles.push(
      `<div class="tile"><div class="v">${trendPoints[trendPoints.length - 1]!.avi}</div><div class="l">${t.avi}</div><div class="s">${t.aviSub}</div></div>`,
    )
  if (geo)
    tiles.push(
      `<div class="tile"><div class="v">${geo.score} <span class="grade">(${geo.grade})</span></div><div class="l">${t.geo}</div><div class="s">&nbsp;</div></div>`,
    )
  if (N)
    tiles.push(
      `<div class="tile"><div class="v">${pct(mentioned, N)}%</div><div class="l">${t.mentionRate}</div><div class="s">${t.ofAnswers(mentioned, N)}</div></div>`,
    )
  const brandEntity = sov.entities.find((e) => e.isBrand)
  if (brandEntity && N)
    tiles.push(
      `<div class="tile"><div class="v">${Math.round(brandEntity.share)}%</div><div class="l">${t.sov}</div><div class="s">${t.sovSub}</div></div>`,
    )
  if (N)
    tiles.push(
      `<div class="tile"><div class="v">${sent.negative}</div><div class="l">${t.negAnswers}</div><div class="s">${t.posNeu(sent.positive, sent.neutral)}</div></div>`,
    )
  if (auditSummary)
    tiles.push(
      `<div class="tile"><div class="v">${auditSummary.score}</div><div class="l">${t.siteAudit}</div><div class="s">/100</div></div>`,
    )

  const engineTable = engines.length
    ? `<div class="tablewrap"><table><tr><th>${t.engine}</th><th class="num">${t.answers}</th><th class="num">${t.mention}</th><th class="num">${t.posAvg}</th><th class="num">${t.visibility}</th><th class="num">${t.tone}</th></tr>${engines
        .map(
          (e) =>
            `<tr><td>${esc(ENGINE_LABEL[e.engine] ?? e.engine)}</td><td class="num">${e.total}</td><td class="num"><strong>${e.mentionRate}%</strong></td><td class="num">${e.positionAvg ?? '—'}</td><td class="num">${e.visibilityAvg}</td><td class="num">${e.sentiment.positive}/${e.sentiment.neutral}/${e.sentiment.negative}</td></tr>`,
        )
        .join('')}</table></div><p class="fn">${t.posFootnote}</p>`
    : `<p class="mut">${t.noData}</p>`

  const geoSection = geo
    ? `<h3>${t.geoTitle(geo.score)}</h3><p class="lede">${t.geoLede}</p><div class="chart">${geo.pillars
        .map(
          (p) =>
            `<div class="pillar"><div class="pillar-head"><span>${esc(pillarL[p.label] ?? p.label)}</span><span class="mut">${t.weight} ${Math.round(p.weight * 100)}% · <strong>${p.score}</strong>/100</span></div><div class="bar-track tall"><span class="bar-fill" style="width:${p.score}%"></span></div></div>`,
        )
        .join('')}</div>`
    : ''

  const trendSection =
    trendPoints.length >= 2
      ? `<h3>${t.trend}</h3><div class="chart">${trendSvg(trendPoints)}</div><div class="tablewrap"><table><tr><th>${t.date}</th><th class="num">AVI</th></tr>${trendPoints
          .slice(-14)
          .map((p) => `<tr><td>${esc(p.date)}</td><td class="num">${p.avi}</td></tr>`)
          .join('')}</table></div>`
      : ''

  const sourcesSection = cited.top.length
    ? `<h3>${t.sources}</h3><div class="chart">${cited.top
        .map((d) =>
          bar(d.domain, d.count, cited.top[0]!.count, {
            suffix: '×',
            highlight: d.isOwn,
            note: d.isOwn ? ` <span class="own">${t.ownDomain}</span>` : '',
          }),
        )
        .join('')}</div><p class="mut">${t.byCategory}: ${cited.byCategory
        .slice(0, 4)
        .map((c) => `${esc(catL[c.category] ?? c.category)} ${pct(c.count, cited.totalCitations)}%`)
        .join(' · ')}</p>`
    : ''

  // Percentages over `mentioned`, not N — the tile copy and the SoV section
  // already treat mentions as the honest denominator for tone.
  const sentimentSection = mentioned
    ? `<h3>${t.sentiment}</h3><div class="chart"><div class="sent-track"><span class="sent-pos" style="width:${pct(sent.positive, mentioned)}%"></span><span class="sent-neu" style="width:${pct(sent.neutral, mentioned)}%"></span><span class="sent-neg" style="width:${pct(sent.negative, mentioned)}%"></span></div><div class="legend"><span><span class="chip" style="background:#0ca30c"></span>${t.positive} ${sent.positive} (${pct(sent.positive, mentioned)}%)</span><span><span class="chip" style="background:#8c8880"></span>${t.neutral} ${sent.neutral} (${pct(sent.neutral, mentioned)}%)</span><span><span class="chip" style="background:#d03b3b"></span>${t.negative} ${sent.negative}</span></div></div>`
    : ''

  const sovMax = sov.entities.length ? Math.max(...sov.entities.map((e) => e.share)) : 0
  const sovSection =
    sov.entities.length > 1
      ? `<h3>${t.competitors}</h3><p class="lede">${t.sovLede}</p><div class="chart">${sov.entities
          .map((e) =>
            bar(e.name, Math.round(e.share), Math.round(sovMax), {
              suffix: '%',
              highlight: e.isBrand,
              note:
                !e.isBrand && !configuredKeys.has(normalizeEntityName(e.name))
                  ? ` <span class="flag">${t.notConfigured}</span>`
                  : '',
            }),
          )
          .join(
            '',
          )}${sov.discoveredShare > 0 ? `<p class="fn">${t.discovered(Math.round(sov.discoveredShare))}</p>` : ''}</div>`
      : ''

  const keywordSection =
    keywords.length >= 5
      ? `<h3>${t.keywords}</h3><p class="lede">${t.keywordsLede}</p><div class="chart">${keywords
          .map((k) =>
            bar(k.keyword, k.mention_count ?? 0, keywords[0]!.mention_count ?? 1, { suffix: '×' }),
          )
          .join('')}</div>`
      : ''

  const auditSection = auditSummary
    ? `<div class="section"><h2>${t.siteAudit}</h2><p class="lede">${t.siteAuditLede(auditSummary.score, esc(String(auditSummary.cachedAt).slice(0, 10)))}</p>${
        auditSummary.topIssues?.length
          ? `<ul>${auditSummary.topIssues
              .slice(0, 6)
              .map((i: string) => `<li>${esc(i)}</li>`)
              .join('')}</ul>`
          : ''
      }</div>`
    : ''

  const recSection = geo?.recommendations.length
    ? `<div class="section"><h2>${t.recommendations}</h2><p class="lede">${t.recLede}</p>${geo.recommendations
        .map(
          (r, i) =>
            `<div class="rec"><div class="rec-head"><span class="rec-rank">${i + 1}</span><strong>${esc(pillarL[r.label] ?? r.label)}</strong><span class="rec-uplift">${t.uplift(r.upliftPts)}</span></div><p class="rec-why">${esc(r.why)} <span class="mut">(${t.pillarNow(pillarL[r.label] ?? r.label, r.currentScore)})</span></p><ul>${r.actions.map((a) => `<li>${esc(a)}</li>`).join('')}</ul></div>`,
        )
        .join('')}</div>`
    : ''

  const qaSection = qa.length
    ? `<div class="section"><h2>${t.qa}</h2><p class="lede">${t.qaLede(qa.length)}</p>${qa
        .map(
          (p, idx) =>
            `<details class="pd"${idx === 0 ? ' open' : ''}><summary><span class="pd-rate">${p.mentionRate}%</span><span class="pd-text">${esc(p.text)}</span><span class="pd-meta">${p.runs} ${t.runs}</span></summary>${p.answers
              .map(
                (a) =>
                  `<div class="answer"><div class="answer-head"><strong>${esc(ENGINE_LABEL[a.engine] ?? a.engine)}</strong>${
                    a.mentioned
                      ? `<span class="b ok">${t.mentioned}${a.mentionPosition != null ? ` · ${t.sentence} ${a.mentionPosition}` : ''}</span>`
                      : `<span class="b no">${t.notMentioned}</span>`
                  }${a.sentiment ? `<span class="b">${esc(a.sentiment)}</span>` : ''}<span class="mut ml">${esc(a.date)}</span></div><p class="answer-text">${esc(a.responseText)}</p>${
                    a.citedUrls.length
                      ? `<ul class="answer-urls">${a.citedUrls.map((u) => `<li><a href="${esc(u)}" rel="noopener noreferrer" target="_blank">${esc(u)}</a></li>`).join('')}</ul>`
                      : ''
                  }</div>`,
              )
              .join('')}</details>`,
        )
        .join('')}</div>`
    : ''

  const html = `<!DOCTYPE html>
<html lang="${locale}">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(brandName)} — ${t.title}</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:system-ui,-apple-system,'Segoe UI',sans-serif;background:#f7f6f3;color:#1c1917;line-height:1.6;padding:24px}
.container{max-width:880px;margin:0 auto;background:#fcfcfb;border:1px solid #e5e2da;border-radius:6px;padding:44px 52px}
@media(max-width:700px){.container{padding:24px 18px}}
h1{font-family:Georgia,serif;font-size:32px}
h2{font-family:Georgia,serif;font-size:21px;margin-bottom:6px}
h3{font-family:Georgia,serif;font-size:16.5px;margin:22px 0 6px}
p{margin:8px 0;max-width:70ch}
.eyebrow{font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:${brandColor};font-weight:700}
.masthead{border-bottom:3px solid ${brandColor};padding-bottom:18px;margin-bottom:24px}
.masthead .meta{display:flex;flex-wrap:wrap;gap:4px 20px;margin-top:8px;color:#57534e;font-size:13px}
.section{margin-top:36px;border-top:1px solid #e5e2da;padding-top:22px}
.lede{color:#57534e}
.mut{color:#8c8880}.fn{font-size:12.5px;color:#8c8880}.ml{margin-left:auto}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:11px;margin:16px 0 4px}
.tile{background:#fff;border:1px solid #e5e2da;border-radius:6px;padding:12px 14px}
.tile .v{font-size:27px;font-weight:700}.tile .grade{font-size:15px;color:#8c8880}
.tile .l{font-size:11px;color:#8c8880;text-transform:uppercase;letter-spacing:.07em;margin-top:2px}
.tile .s{font-size:12px;color:#57534e;margin-top:2px}
table{width:100%;border-collapse:collapse;font-size:14px}
th{font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:#8c8880;text-align:left;font-weight:600;padding:6px 10px;border-bottom:1px solid #e5e2da}
td{padding:7px 10px;border-bottom:1px solid #e5e2da}
td.num,th.num{text-align:right;font-variant-numeric:tabular-nums}
.tablewrap{overflow-x:auto;border:1px solid #e5e2da;border-radius:6px;margin:12px 0}
.chart{background:#fff;border:1px solid #e5e2da;border-radius:6px;padding:16px 16px 10px;margin:12px 0}
svg{width:100%;height:auto;display:block}
.tick{font:11px system-ui,sans-serif;fill:#8c8880}
.bar-row{display:grid;grid-template-columns:220px 1fr 52px;gap:12px;align-items:center;padding:4px 0}
@media(max-width:640px){.bar-row{grid-template-columns:130px 1fr 46px}}
.bar-label{font-size:13.5px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.bar-track{background:#e7e4dc;border-radius:4px;height:13px;overflow:hidden}
.bar-track.tall{height:11px;margin-top:4px}
.bar-fill{display:block;height:100%;background:#2a78d6;border-radius:0 4px 4px 0}
.bar-fill.hl{background:#c98500}
.bar-val{font-size:13px;text-align:right;font-variant-numeric:tabular-nums;color:#57534e}
.pillar{margin:10px 0}.pillar-head{display:flex;justify-content:space-between;font-size:13.5px}
.own{display:inline-block;background:#fdf6e3;color:#a16207;font-size:10.5px;font-weight:700;padding:1px 7px;border-radius:99px;margin-left:6px}
.flag{display:inline-block;background:#fbeaea;color:#a03434;font-size:10.5px;font-weight:700;padding:1px 7px;border-radius:99px;margin-left:6px}
.sent-track{display:flex;height:17px;border-radius:4px;overflow:hidden;gap:2px}
.sent-pos{background:#0ca30c}.sent-neu{background:#8c8880}.sent-neg{background:#d03b3b}
.legend{display:flex;flex-wrap:wrap;gap:16px;font-size:12.5px;color:#57534e;margin-top:8px}
.legend .chip{display:inline-block;width:10px;height:10px;border-radius:2px;margin-right:5px;vertical-align:-1px}
.rec{border:1px solid #e5e2da;border-radius:6px;padding:14px 18px;margin:10px 0;background:#fff}
.rec-head{display:flex;align-items:center;gap:10px}
.rec-rank{font-family:Georgia,serif;font-weight:700;color:${brandColor};border:1.5px solid ${brandColor};border-radius:99px;width:23px;height:23px;display:inline-flex;align-items:center;justify-content:center;font-size:12.5px}
.rec-uplift{margin-left:auto;font-size:12px;font-weight:700;color:#0a7d0a}
.rec-why{font-size:13.5px;color:#57534e}.rec ul{margin:6px 0 2px;padding-left:20px;font-size:13.5px}
.pd{border:1px solid #e5e2da;border-radius:6px;margin:9px 0;background:#fff}
.pd summary{display:flex;align-items:center;gap:12px;padding:11px 14px;cursor:pointer;list-style:none}
.pd summary::-webkit-details-marker{display:none}
.pd-rate{font-weight:700;font-variant-numeric:tabular-nums;min-width:42px;color:${brandColor}}
.pd-text{flex:1;font-size:14px}.pd-meta{font-size:11.5px;color:#8c8880;white-space:nowrap}
.answer{border-top:1px solid #e5e2da;padding:11px 14px}
.answer-head{display:flex;align-items:center;gap:8px;flex-wrap:wrap;font-size:12.5px;margin-bottom:4px}
.b{background:#e7e4dc;border-radius:99px;font-size:11px;padding:1px 8px;color:#57534e}
.b.ok{background:#fdf6e3;color:#a16207;font-weight:700}.b.no{background:#fbeaea;color:#a03434}
.answer-text{font-size:13px;color:#57534e;white-space:pre-wrap;max-width:none}
.answer-urls{margin:6px 0 0;padding-left:18px;font-size:11.5px}
.answer-urls a{color:${brandColor};word-break:break-all}
ul{padding-left:20px}li{margin:3px 0;font-size:14px}
.footer{margin-top:32px;padding-top:14px;border-top:1px solid #e5e2da;font-size:12px;color:#8c8880}
@media print{body{padding:0}.container{border:none}.section{break-inside:avoid-page}.pd{break-inside:avoid}}
</style>
</head>
<body>
<div class="container">
  <header class="masthead">
    <div class="eyebrow">${t.title}</div>
    <h1>${esc(brandName)}</h1>
    <div class="meta">
      <span><strong>${t.period}</strong> ${esc(fromDate)} – ${esc(toDate)}</span>
      ${brandDomain ? `<span><strong>Domain</strong> ${esc(brandDomain)}</span>` : ''}
      <span><strong>${t.engines}</strong> ${engines.map((e) => ENGINE_LABEL[e.engine] ?? e.engine).join(' · ') || '—'}</span>
      <span><strong>${t.preparedBy}</strong> AEO Pulse</span>
    </div>
  </header>

  <section>
    <h2>${t.summary}</h2>
    <p class="lede">${t.summaryLede(N, qa.length || prompts.length, trendPoints.length || days)}</p>
    <div class="tiles">${tiles.join('')}</div>
  </section>

  <section class="section">
    <h2>${t.monitoring}</h2>
    <p class="lede">${t.monitoringLede}</p>
    ${engineTable}
  </section>

  ${geoSection || trendSection || sourcesSection || sentimentSection || sovSection || keywordSection ? `<section class="section"><h2>${t.insights}</h2>${geoSection}${trendSection}${sourcesSection}${sentimentSection}${sovSection}${keywordSection}</section>` : ''}

  ${auditSection}
  ${recSection}
  ${qaSection}

  <section class="section">
    <h2>${t.method}</h2>
    <p class="fn">${esc(geoMethodologyNote(locale))}</p>
  </section>

  <div class="footer">${t.generated} AEO Pulse · ${new Date().toISOString().split('T')[0]}</div>
</div>
</body>
</html>`

  const headers: Record<string, string> = { 'Content-Type': 'text/html; charset=utf-8' }
  if (download) {
    const safeName =
      String(brandName)
        .replace(/[^a-zA-Z0-9_-]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .slice(0, 60) || 'report'
    headers['Content-Disposition'] =
      `attachment; filename="${safeName}-report-${fromDate}-${toDate}.html"`
  }

  return new NextResponse(html, { headers })
}
