export interface LlmsInput {
  brandName: string
  domain: string
  description?: string
  industry?: string
  competitors?: string[]
  aliases?: string[]
  products?: Array<{ name: string; description: string }>
  keyFacts?: { founded?: string; headquarters?: string; specialties?: string[]; employees?: string }
  importantPages?: Array<{ title: string; url: string; description: string }>
  faqs?: Array<{ question: string; answer: string }>
}

export function generateLlmsTxt(input: LlmsInput): string {
  const { brandName, domain, description, products, keyFacts, importantPages } = input

  const lines: string[] = []

  lines.push(`# ${brandName}`)
  if (description) {
    lines.push(`> ${description}`)
  }
  lines.push('')

  if (description) {
    lines.push('## About')
    lines.push(description)
    lines.push('')
  }

  if (products && products.length > 0) {
    lines.push('## Products & Services')
    for (const product of products) {
      lines.push(`- ${product.name}: ${product.description}`)
    }
    lines.push('')
  }

  const hasKeyFacts =
    keyFacts &&
    (keyFacts.founded || keyFacts.headquarters || keyFacts.specialties || keyFacts.employees)

  if (hasKeyFacts) {
    lines.push('## Key Facts')
    if (keyFacts!.founded) {
      lines.push(`- Founded: ${keyFacts!.founded}`)
    }
    if (keyFacts!.headquarters) {
      lines.push(`- Headquarters: ${keyFacts!.headquarters}`)
    }
    if (keyFacts!.specialties && keyFacts!.specialties.length > 0) {
      lines.push(`- Specialties: ${keyFacts!.specialties.join(', ')}`)
    }
    if (keyFacts!.employees) {
      lines.push(`- Employees: ${keyFacts!.employees}`)
    }
    lines.push('')
  }

  if (importantPages && importantPages.length > 0) {
    lines.push('## Important Links')
    lines.push(`- [Homepage](https://${domain}): Main website`)
    for (const page of importantPages) {
      lines.push(`- [${page.title}](${page.url}): ${page.description}`)
    }
  }

  return lines.join('\n').trim() + '\n'
}

export function generateLlmsFullTxt(input: LlmsInput): string {
  const {
    brandName,
    domain,
    description,
    industry,
    competitors,
    aliases,
    products,
    keyFacts,
    importantPages,
    faqs,
  } = input

  const lines: string[] = []
  const today = new Date().toISOString().split('T')[0]

  lines.push(`# ${brandName}`)
  if (description) {
    lines.push(`> ${description}`)
  }
  lines.push('')

  if (description) {
    lines.push('## About')
    lines.push(description)
    lines.push('')
  }

  lines.push('## Brand Identity')
  lines.push(`- **Official Name**: ${brandName}`)
  if (aliases && aliases.length > 0) {
    lines.push(`- **Also Known As**: ${aliases.join(', ')}`)
  }
  lines.push(`- **Website**: https://${domain}`)
  if (industry) {
    lines.push(`- **Industry**: ${industry}`)
  }
  lines.push('')

  if (products && products.length > 0) {
    lines.push('## Products & Services')
    for (const product of products) {
      lines.push(`### ${product.name}`)
      lines.push(product.description)
      lines.push('')
    }
  }

  const hasKeyFacts =
    keyFacts &&
    (keyFacts.founded || keyFacts.headquarters || keyFacts.specialties || keyFacts.employees)

  if (hasKeyFacts) {
    lines.push('## Company Information')
    if (keyFacts!.founded) {
      lines.push(`- **Founded**: ${keyFacts!.founded}`)
    }
    if (keyFacts!.headquarters) {
      lines.push(`- **Headquarters**: ${keyFacts!.headquarters}`)
    }
    if (keyFacts!.specialties && keyFacts!.specialties.length > 0) {
      lines.push(`- **Specialties**: ${keyFacts!.specialties.join(', ')}`)
    }
    if (keyFacts!.employees) {
      lines.push(`- **Employees**: ${keyFacts!.employees}`)
    }
    lines.push('')
  }

  if (faqs && faqs.length > 0) {
    lines.push('## Frequently Asked Questions')
    for (const faq of faqs) {
      lines.push(`### ${faq.question}`)
      lines.push(faq.answer)
      lines.push('')
    }
  }

  if (importantPages && importantPages.length > 0) {
    lines.push('## Important Links')
    lines.push(`- [Homepage](https://${domain}): Main website`)
    for (const page of importantPages) {
      lines.push(`- [${page.title}](${page.url}): ${page.description}`)
    }
    lines.push('')
  }

  if (competitors && competitors.length > 0) {
    lines.push('## Market Context')
    lines.push(`**Competitors**: ${competitors.join(', ')}`)
    lines.push('')
  }

  lines.push('---')
  lines.push(`Generated by AIO Pulse Advance | ${today}`)

  return lines.join('\n').trim() + '\n'
}
