import { jsPDF } from 'jspdf'
import type { Brand } from '@/types'
import { calculateAVIFromResults, calculateDomainSOAIV, calculateCompetitorAVI } from './monitoring'

export interface PdfReportData {
  brandName: string
  fromDate: string
  toDate: string
  results: Array<{
    created_at: string
    engine: string
    brand_mentioned: boolean
    visibility_score: number
    sentiment: string | null
    sentiment_score: number | null
    url: string | null
    cited_urls?: string[]
    has_hallucination?: boolean
    competitor_mentions?: Array<{ name: string; position: number; count: number }>
  }>
  sentimentHistory?: Array<{
    snapshot_date: string
    sentiment_score: number
    positive_count: number
    neutral_count: number
    negative_count: number
  }>
  recommendations?: Array<{
    recommendation_text: string
    priority: string | null
    category: string | null
  }>
  competitors?: string[]
}

export interface PdfGeneratorOptions {
  locale?: string
}

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const cleanHex = hex?.replace('#', '') || '6366f1'
  const result = /^([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(cleanHex)
  if (!result) return { r: 99, g: 102, b: 241 }
  return {
    r: parseInt(result[1] || '63', 16),
    g: parseInt(result[2] || '66', 16),
    b: parseInt(result[3] || 'f1', 16),
  }
}

function addFooter(doc: jsPDF, brandName: string, pageCount: number): void {
  const pageWidth = doc.internal.pageSize.getWidth()
  const footerColor = hexToRgb('#888888')
  doc.setFontSize(8)
  doc.setTextColor(footerColor.r, footerColor.g, footerColor.b)
  const currentPage = doc.getCurrentPageInfo().pageNumber
  doc.text(`Generated by ${brandName} - Page ${currentPage} of ${pageCount}`, pageWidth / 2, 288, {
    align: 'center',
  })
}

function addHeader(
  doc: jsPDF,
  brand: Brand,
  title: string,
  primaryColor: { r: number; g: number; b: number },
): void {
  const pageWidth = doc.internal.pageSize.getWidth()

  doc.setFillColor(primaryColor.r, primaryColor.g, primaryColor.b)
  doc.rect(0, 0, pageWidth, 25, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(brand.report_brand_name || 'AIO Pulse', 15, 16)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(title, pageWidth - 15, 16, { align: 'right' })

  if (brand.report_logo_url) {
    try {
      doc.addImage(brand.report_logo_url, 'PNG', pageWidth - 45, 3, 20, 10)
    } catch {
      // Skip if image fails
    }
  }
}

export async function generatePdf(
  brand: Brand,
  data: PdfReportData,
  options: PdfGeneratorOptions = {},
): Promise<Buffer> {
  const { locale = 'en' } = options
  const primaryColor = hexToRgb(brand.report_primary_color || '#6366f1')
  const brandName = brand.report_brand_name || 'AIO Pulse'
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 15

  const totalPages = 4

  // Page 1: AVI + SOAIV
  doc.addPage()
  addHeader(doc, brand, `Brand Report: ${data.brandName}`, primaryColor)

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text(`Report Period: ${data.fromDate} to ${data.toDate}`, margin, 35)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.setFontSize(10)
  doc.text(`Locale: ${locale.toUpperCase()}`, margin, 42)

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('1. AVI & Share of AI Voice Analysis', margin, 55)

  const aviResults = data.results.map((r) => ({
    brand_mentioned: r.brand_mentioned,
    visibility_score: r.visibility_score,
    sentiment_score: r.sentiment_score ?? 0,
    cited_urls: r.cited_urls ?? [],
    has_hallucination: r.has_hallucination ?? false,
    mention_position: r.competitor_mentions?.[0]?.position ?? null,
  }))
  const { avi, components } = calculateAVIFromResults(aviResults)
  const soaivResults =
    data.results.length > 0 && brand.domain
      ? calculateDomainSOAIV(
          data.results.map((r) => r.url).filter(Boolean) as string[],
          brand.domain,
          brand.competitors || [],
        )
      : []

  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('AVI Score Components:', margin, 65)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)

  const componentLabels: Record<string, string> = {
    mentionRate: 'Mention Rate',
    avgVisibility: 'Avg Visibility',
    avgPosition: 'Avg Position',
    avgSentiment: 'Avg Sentiment',
    citationRate: 'Citation Rate',
    hallucinationPenalty: 'Hallucination Penalty',
  }

  let yPos = 73
  Object.entries(components).forEach(([key, value]) => {
    doc.text(
      `${componentLabels[key] || key}: ${typeof value === 'number' ? value.toFixed(1) : value}`,
      margin,
      yPos,
    )
    yPos += 6
  })

  doc.setFillColor(primaryColor.r, primaryColor.g, primaryColor.b)
  doc.roundedRect(margin, yPos + 5, 50, 25, 3, 3, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text(avi.toFixed(1), margin + 25, yPos + 17, { align: 'center' })
  doc.setFontSize(8)
  doc.text('AVI Score', margin + 25, yPos + 23, { align: 'center' })

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Share of AI Voice (SOAIV)', margin, 115)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')

  yPos = 125
  if (soaivResults.length > 0) {
    soaivResults.forEach((result) => {
      doc.text(
        `${result.domain}: ${result.brandShare.toFixed(1)}% (mentions: ${result.brandShare > 0 ? 'brand' : 'none'})`,
        margin,
        yPos,
      )
      yPos += 6
    })
  } else {
    doc.text('No SOAIV data available', margin, yPos)
  }

  addFooter(doc, brandName, totalPages)

  // Page 2: Competitor Gap
  doc.addPage()
  addHeader(doc, brand, `Competitor Analysis: ${data.brandName}`, primaryColor)

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('2. Competitor Gap Analysis', margin, 35)

  doc.setFontSize(11)
  doc.text('Comparing brand AVI against competitors:', margin, 45)

  yPos = 55
  const competitorList = data.competitors || brand.competitors || []

  if (competitorList.length > 0) {
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text('Competitor', margin, yPos)
    doc.text('AVI', margin + 60, yPos)
    doc.text('Gap', margin + 90, yPos)
    doc.text('Status', margin + 120, yPos)
    yPos += 2
    doc.line(margin, yPos, pageWidth - margin, yPos)
    yPos += 6
    doc.setFont('helvetica', 'normal')

    for (const competitor of competitorList) {
      const competitorMentions = data.results
        .filter((r) =>
          r.competitor_mentions?.some((c) => c.name.toLowerCase() === competitor.toLowerCase()),
        )
        .flatMap((r) => r.competitor_mentions || [])
        .filter((c) => c.name.toLowerCase() === competitor.toLowerCase())

      const result = calculateCompetitorAVI(competitorMentions, avi)
      const gap = avi - result.competitorAvi
      const statusLabel =
        result.rank === 1
          ? 'Leader'
          : result.rank === 2
            ? 'Close'
            : result.rank === 3
              ? 'Behind'
              : 'N/A'

      doc.text(competitor, margin, yPos)
      doc.text(result.competitorAvi.toFixed(1), margin + 60, yPos)
      doc.text(gap > 0 ? `+${gap.toFixed(1)}` : gap.toFixed(1), margin + 90, yPos)
      doc.text(statusLabel, margin + 120, yPos)
      yPos += 8
    }
  } else {
    doc.text('No competitors configured', margin, yPos)
  }

  addFooter(doc, brandName, totalPages)

  // Page 3: Sentiment Heatmap
  doc.addPage()
  addHeader(doc, brand, `Sentiment Analysis: ${data.brandName}`, primaryColor)

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('3. Sentiment Heatmap', margin, 35)

  const sentimentData = data.sentimentHistory || []

  yPos = 50
  if (sentimentData.length > 0) {
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text('Date', margin, yPos)
    doc.text('Positive', margin + 35, yPos)
    doc.text('Neutral', margin + 65, yPos)
    doc.text('Negative', margin + 95, yPos)
    doc.text('Score', margin + 125, yPos)
    yPos += 2
    doc.line(margin, yPos, pageWidth - margin, yPos)
    yPos += 6
    doc.setFont('helvetica', 'normal')

    for (const entry of sentimentData.slice(0, 15)) {
      doc.text(entry.snapshot_date || '', margin, yPos)
      doc.text(String(entry.positive_count), margin + 35, yPos)
      doc.text(String(entry.neutral_count), margin + 65, yPos)
      doc.text(String(entry.negative_count), margin + 95, yPos)
      doc.text(entry.sentiment_score.toFixed(2), margin + 125, yPos)
      yPos += 7
    }
  } else {
    const statsMap: Record<
      string,
      { positive: number; neutral: number; negative: number; total: number }
    > = {}

    data.results.forEach((r) => {
      const engineKey = r.engine
      if (!statsMap[engineKey]) {
        statsMap[engineKey] = { positive: 0, neutral: 0, negative: 0, total: 0 }
      }
      const entry = statsMap[engineKey]
      entry.total++
      if (r.sentiment === 'positive') entry.positive++
      else if (r.sentiment === 'negative') entry.negative++
      else entry.neutral++
    })

    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text('Engine', margin, yPos)
    doc.text('Positive %', margin + 35, yPos)
    doc.text('Neutral %', margin + 70, yPos)
    doc.text('Negative %', margin + 105, yPos)
    yPos += 2
    doc.line(margin, yPos, pageWidth - margin, yPos)
    yPos += 6
    doc.setFont('helvetica', 'normal')

    Object.entries(statsMap).forEach(([engine, stats]) => {
      const posPct = stats.total > 0 ? ((stats.positive / stats.total) * 100).toFixed(0) : '0'
      const neuPct = stats.total > 0 ? ((stats.neutral / stats.total) * 100).toFixed(0) : '0'
      const negPct = stats.total > 0 ? ((stats.negative / stats.total) * 100).toFixed(0) : '0'

      doc.text(engine, margin, yPos)
      doc.text(`${posPct}%`, margin + 35, yPos)
      doc.text(`${neuPct}%`, margin + 70, yPos)
      doc.text(`${negPct}%`, margin + 105, yPos)
      yPos += 7
    })
  }

  const avgSentiment =
    data.results.length > 0
      ? data.results.reduce((sum, r) => sum + (r.sentiment_score || 0), 0) / data.results.length
      : 0

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text(`Overall Sentiment Score: ${avgSentiment.toFixed(2)}`, margin, yPos + 10)

  addFooter(doc, brandName, totalPages)

  // Page 4: Recommendations
  doc.addPage()
  addHeader(doc, brand, `Recommendations: ${data.brandName}`, primaryColor)

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('4. Recommendations', margin, 35)

  const recommendations = data.recommendations || []
  yPos = 48

  if (recommendations.length > 0) {
    recommendations.forEach((rec, index) => {
      if (yPos > pageHeight - 30) {
        addFooter(doc, brandName, totalPages)
        doc.addPage()
        addHeader(doc, brand, `Recommendations: ${data.brandName}`, primaryColor)
        doc.setTextColor(0, 0, 0)
        yPos = 35
      }

      const priorityColor =
        rec.priority === 'high'
          ? { r: 220, g: 38, b: 38 }
          : rec.priority === 'medium'
            ? { r: 245, g: 158, b: 11 }
            : { r: 34, g: 197, b: 94 }

      doc.setFillColor(priorityColor.r, priorityColor.g, priorityColor.b)
      doc.circle(margin + 2, yPos - 1, 2, 'F')

      doc.setFontSize(11)
      doc.setFont('helvetica', 'bold')
      doc.text(`${index + 1}. ${rec.category || 'General'}`, margin + 10, yPos)

      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      const lines = doc.splitTextToSize(rec.recommendation_text, pageWidth - margin - 15)
      doc.text(lines, margin + 10, yPos + 6)

      yPos += 6 + lines.length * 5 + 8
    })
  } else {
    const defaultRecommendations = [
      {
        category: 'Visibility',
        text: 'Increase brand mentions in AI responses by optimizing content for AI comprehension.',
      },
      {
        category: 'Citations',
        text: 'Aim for more first-position citations by strengthening authoritative content.',
      },
      {
        category: 'Sentiment',
        text: 'Monitor and address negative sentiment patterns in AI-generated responses.',
      },
      {
        category: 'Competitors',
        text: 'Analyze competitor strategies to identify gaps and opportunities.',
      },
    ]

    defaultRecommendations.forEach((rec, index) => {
      doc.setFontSize(11)
      doc.setFont('helvetica', 'bold')
      doc.text(`${index + 1}. ${rec.category}`, margin, yPos)

      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      const lines = doc.splitTextToSize(rec.text, pageWidth - margin - 10)
      doc.text(lines, margin, yPos + 6)

      yPos += 6 + lines.length * 5 + 8
    })
  }

  addFooter(doc, brandName, totalPages)

  const pdfBuffer = doc.output('arraybuffer')
  return Buffer.from(pdfBuffer)
}
