// PATH: src/lib/services/weekly-review.ts

export interface WeeklyReviewData {
  brandId: string
  brandName: string
  weekStart: string
  weekEnd: string
  weekNumber: number
  metrics: {
    aviScoreCurrent: number
    aviScorePrevious: number
    aviDelta: number
    totalMonitoringRuns: number
    newHallucinations: number
    mentionRate: number
    citationRate: number
    avgSentiment: number
  }
  highlight: string
  concern: string
  obsidianNote: string
}

function getISOWeek(date: Date): number {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()))
  d.setUTCDate(d.getUTCDate() + 4 - (d.getUTCDay() || 7))
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1))
  return Math.ceil(((d.getTime() - yearStart.getTime()) / 86400000 + 1) / 7)
}

export async function generateWeeklyReview(
  supabase: any,
  brandId: string,
  brandName: string,
  userId: string,
): Promise<WeeklyReviewData> {
  const now = new Date()

  // Last full week: Monday to Sunday
  const weekEnd = new Date(now)
  weekEnd.setDate(now.getDate() - now.getDay()) // Last Sunday
  const weekStart = new Date(weekEnd)
  weekStart.setDate(weekEnd.getDate() - 6)

  const startStr = weekStart.toISOString().split('T')[0] as string
  const endStr = weekEnd.toISOString().split('T')[0] as string
  const weekNumber = getISOWeek(weekStart)

  // Current health score (latest within range or before)
  const { data: currentScore } = await supabase
    .from('brand_health_scores')
    .select('*')
    .eq('brand_id', brandId)
    .lte('date', endStr)
    .order('date', { ascending: false })
    .limit(1)

  // Previous week health score
  const prevWeekEnd = new Date(weekStart)
  prevWeekEnd.setDate(prevWeekEnd.getDate() - 1)
  const { data: prevScore } = await supabase
    .from('brand_health_scores')
    .select('avi_score, health_score')
    .eq('brand_id', brandId)
    .lte('date', prevWeekEnd.toISOString().split('T')[0])
    .order('date', { ascending: false })
    .limit(1)

  // Count monitoring results this week
  const { count: monitoringCount } = await supabase
    .from('monitoring_results')
    .select('*', { count: 'exact', head: true })
    .eq('brand_id', brandId)
    .gte('created_at', startStr)
    .lte('created_at', endStr + 'T23:59:59')

  // Count new hallucinations
  const { count: newHals } = await supabase
    .from('monitoring_results')
    .select('*', { count: 'exact', head: true })
    .eq('brand_id', brandId)
    .eq('has_hallucination', true)
    .gte('created_at', startStr)
    .lte('created_at', endStr + 'T23:59:59')

  const cs = currentScore?.[0]
  const currentAvi = cs?.avi_score ?? cs?.health_score ?? 0
  const prevAvi = prevScore?.[0]?.avi_score ?? prevScore?.[0]?.health_score ?? 0

  const metrics = {
    aviScoreCurrent: currentAvi,
    aviScorePrevious: prevAvi,
    aviDelta: Math.round((currentAvi - prevAvi) * 10) / 10,
    totalMonitoringRuns: monitoringCount ?? 0,
    newHallucinations: newHals ?? 0,
    mentionRate: cs?.mention_rate ?? cs?.visibility_score ?? 0,
    citationRate: cs?.citation_rate ?? 0,
    avgSentiment: cs?.sentiment_score ?? 0,
  }

  const highlight =
    metrics.aviDelta > 0
      ? `AVI improved by ${metrics.aviDelta} points this week`
      : metrics.totalMonitoringRuns > 0
        ? `${metrics.totalMonitoringRuns} monitoring checks completed`
        : 'Monitoring active, data accumulating'

  const concern =
    metrics.newHallucinations > 0
      ? `${metrics.newHallucinations} new hallucination(s) detected — review required`
      : metrics.aviDelta < -5
        ? `AVI dropped by ${Math.abs(metrics.aviDelta)} points — investigate cause`
        : 'No critical concerns this week'

  const today = new Date().toISOString().split('T')[0]
  const obsidianNote = `---
type: weekly-review
client: "${brandName}"
status: active
created: ${today}
updated: ${today}
tags: [weekly-review, monitoring, auto-generated]
week_number: ${weekNumber}
year: ${weekStart.getFullYear()}
clients_monitored: ["${brandName}"]
new_hallucinations: ${metrics.newHallucinations}
actions_completed: 0
actions_created: 0
highlight: "${highlight}"
concern: "${concern}"
---

# Weekly Review — ${brandName} — W${weekNumber} ${weekStart.getFullYear()}

**Period:** ${startStr} → ${endStr}
**Generated:** Auto-generated by AEO Pulse

## Key Metrics

| Metric | Value | Δ vs Last Week |
|--------|-------|----------------|
| AVI Score | ${metrics.aviScoreCurrent.toFixed(1)} | ${metrics.aviDelta > 0 ? '+' : ''}${metrics.aviDelta.toFixed(1)} |
| Mention Rate | ${metrics.mentionRate.toFixed(1)}% | — |
| Citation Rate | ${metrics.citationRate.toFixed(1)}% | — |
| Sentiment | ${metrics.avgSentiment.toFixed(2)} | — |
| Monitoring Runs | ${metrics.totalMonitoringRuns} | — |
| New Hallucinations | ${metrics.newHallucinations} | — |

## Highlights
${highlight}

## Concerns
${concern}

## Next Week Priorities
1. Review any new hallucinations
2. Continue monitoring schedule
3. Track AVI trend

## Notes
Auto-generated weekly review. Edit in Obsidian for additional observations.
`

  return {
    brandId,
    brandName,
    weekStart: startStr,
    weekEnd: endStr,
    weekNumber,
    metrics,
    highlight,
    concern,
    obsidianNote,
  }
}
