-- Migration: update user_api_keys.provider allowed values
-- Removes Groq / Cerebras / OpenRouter (decommissioned 2026-04-12).
-- New allowed providers: openai, gemini, perplexity, anthropic.
-- Apply BEFORE deploying the refactored app; otherwise the CHECK constraint
-- will still accept the old values and reject the new ones.

BEGIN;

-- 1. Delete rows with decommissioned providers. These API keys are useless
--    now that the corresponding providers are removed from the codebase.
DELETE FROM user_api_keys
WHERE provider IN ('groq', 'cerebras', 'openrouter');

-- 2. Drop the old CHECK constraint (name is auto-generated by Postgres,
--    so discover it dynamically).
DO $$
DECLARE
  constraint_name text;
BEGIN
  SELECT conname INTO constraint_name
  FROM pg_constraint
  WHERE conrelid = 'user_api_keys'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) ILIKE '%provider%';

  IF constraint_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE user_api_keys DROP CONSTRAINT %I', constraint_name);
  END IF;
END $$;

-- 3. Add the new CHECK constraint with the 4 core providers.
ALTER TABLE user_api_keys
  ADD CONSTRAINT user_api_keys_provider_check
  CHECK (provider IN ('openai', 'gemini', 'perplexity', 'anthropic'));

COMMIT;
