import { describe, it, expect } from 'vitest'
import {
  generateLlmsTxt,
  generateLlmsFullTxt,
  type LlmsInput,
} from '../services/llms-generator'

const baseInput: LlmsInput = {
  brandName: 'Acme Corp',
  domain: 'acme.com',
  description: 'B2B SaaS platform for workflow automation',
  industry: 'Software',
  aliases: ['Acme', 'AcmeCorp'],
  competitors: ['Zapier', 'Make'],
  products: [
    { name: 'Acme Flow', description: 'Visual workflow builder' },
    { name: 'Acme Connect', description: '500+ integrations' },
  ],
  keyFacts: {
    founded: '2015',
    headquarters: 'Stockholm, Sweden',
    specialties: ['automation', 'integration', 'SaaS'],
    employees: '150-200',
  },
  importantPages: [
    { title: 'Pricing', url: 'https://acme.com/pricing', description: 'Plans and pricing' },
    { title: 'Docs', url: 'https://acme.com/docs', description: 'API documentation' },
  ],
  faqs: [
    { question: 'What is Acme Flow?', answer: 'A visual automation builder' },
    { question: 'Do you offer a free tier?', answer: 'Yes, up to 100 runs/month' },
  ],
}

describe('generateLlmsTxt', () => {
  it('starts with the brand H1 heading', () => {
    const out = generateLlmsTxt(baseInput)
    expect(out.startsWith('# Acme Corp')).toBe(true)
  })

  it('includes blockquote description', () => {
    const out = generateLlmsTxt(baseInput)
    expect(out).toContain('> B2B SaaS platform for workflow automation')
  })

  it('includes Products & Services section when products present', () => {
    const out = generateLlmsTxt(baseInput)
    expect(out).toContain('## Products & Services')
    expect(out).toContain('- Acme Flow: Visual workflow builder')
    expect(out).toContain('- Acme Connect: 500+ integrations')
  })

  it('includes Key Facts section with all fields', () => {
    const out = generateLlmsTxt(baseInput)
    expect(out).toContain('## Key Facts')
    expect(out).toContain('- Founded: 2015')
    expect(out).toContain('- Headquarters: Stockholm, Sweden')
    expect(out).toContain('- Specialties: automation, integration, SaaS')
    expect(out).toContain('- Employees: 150-200')
  })

  it('includes Important Links with homepage', () => {
    const out = generateLlmsTxt(baseInput)
    expect(out).toContain('## Important Links')
    expect(out).toContain('[Homepage](https://acme.com): Main website')
    expect(out).toContain('[Pricing](https://acme.com/pricing): Plans and pricing')
  })

  it('omits sections for missing optional fields', () => {
    const minimal: LlmsInput = { brandName: 'Bare', domain: 'bare.io' }
    const out = generateLlmsTxt(minimal)
    expect(out).toContain('# Bare')
    expect(out).not.toContain('## Products')
    expect(out).not.toContain('## Key Facts')
    expect(out).not.toContain('## Important Links')
  })

  it('ends with trailing newline', () => {
    const out = generateLlmsTxt(baseInput)
    expect(out.endsWith('\n')).toBe(true)
  })
})

describe('generateLlmsFullTxt', () => {
  it('is strictly longer than the short variant', () => {
    const short = generateLlmsTxt(baseInput)
    const full = generateLlmsFullTxt(baseInput)
    expect(full.length).toBeGreaterThan(short.length)
  })

  it('includes Brand Identity section', () => {
    const out = generateLlmsFullTxt(baseInput)
    expect(out).toContain('## Brand Identity')
    expect(out).toContain('- **Official Name**: Acme Corp')
    expect(out).toContain('- **Also Known As**: Acme, AcmeCorp')
    expect(out).toContain('- **Website**: https://acme.com')
    expect(out).toContain('- **Industry**: Software')
  })

  it('renders products as H3 headings with body', () => {
    const out = generateLlmsFullTxt(baseInput)
    expect(out).toContain('### Acme Flow')
    expect(out).toContain('Visual workflow builder')
    expect(out).toContain('### Acme Connect')
  })

  it('includes FAQ section with H3 questions', () => {
    const out = generateLlmsFullTxt(baseInput)
    expect(out).toContain('## Frequently Asked Questions')
    expect(out).toContain('### What is Acme Flow?')
    expect(out).toContain('A visual automation builder')
  })

  it('includes Market Context with competitors', () => {
    const out = generateLlmsFullTxt(baseInput)
    expect(out).toContain('## Market Context')
    expect(out).toContain('Zapier, Make')
  })

  it('includes footer with AIO Pulse attribution and ISO date', () => {
    const out = generateLlmsFullTxt(baseInput)
    expect(out).toContain('Generated by AIO Pulse Advance')
    expect(out).toMatch(/\d{4}-\d{2}-\d{2}/)
  })
})
