import { describe, it, expect } from 'vitest'
import { generateLlmsTxt, generateLlmsFullTxt, type LlmsInput } from '../services/llms-generator'

const baseInput: LlmsInput = {
  brandName: 'Acme Corp',
  domain: 'acme.com',
  description: 'B2B SaaS platform for workflow automation',
  industry: 'Software',
  aliases: ['Acme', 'AcmeCorp'],
  competitors: ['Zapier', 'Make'],
  products: [
    { name: 'Acme Flow', description: 'Visual workflow builder' },
    { name: 'Acme Connect', description: '500+ integrations' },
  ],
  keyFacts: {
    founded: '2015',
    headquarters: 'Stockholm, Sweden',
    specialties: ['automation', 'integration', 'SaaS'],
    employees: '150-200',
  },
  importantPages: [
    { title: 'Pricing', url: 'https://acme.com/pricing', description: 'Plans and pricing' },
    { title: 'Docs', url: 'https://acme.com/docs', description: 'API documentation' },
  ],
  faqs: [
    { question: 'What is Acme Flow?', answer: 'A visual automation builder' },
    { question: 'Do you offer a free tier?', answer: 'Yes, up to 100 runs/month' },
  ],
}

describe('generateLlmsTxt (spec-compliant per llmstxt.org)', () => {
  it('starts with the brand H1 heading', () => {
    const out = generateLlmsTxt(baseInput)
    expect(out.startsWith('# Acme Corp')).toBe(true)
  })

  it('includes blockquote summary', () => {
    const out = generateLlmsTxt(baseInput)
    expect(out).toContain('> B2B SaaS platform for workflow automation')
  })

  it('synthesizes a blockquote from industry when no description', () => {
    const out = generateLlmsTxt({ brandName: 'Bare', domain: 'bare.io', industry: 'Retail' })
    expect(out).toContain('> Bare — Retail.')
  })

  it('renders a curated Key Pages link list with the homepage first', () => {
    const out = generateLlmsTxt(baseInput)
    expect(out).toContain('## Key Pages')
    expect(out).toContain('- [Homepage](https://acme.com): Main website')
    expect(out).toContain('- [Pricing](https://acme.com/pricing): Plans and pricing')
    expect(out).toContain('- [Docs](https://acme.com/docs): API documentation')
  })

  it('is link-centric: no content sections (those belong in llms-full.txt)', () => {
    const out = generateLlmsTxt(baseInput)
    expect(out).not.toContain('## Products')
    expect(out).not.toContain('## Key Facts')
    expect(out).not.toContain('## About')
  })

  it('puts overflow links (>5) into an Optional section', () => {
    const manyPages: LlmsInput = {
      brandName: 'Acme Corp',
      domain: 'acme.com',
      importantPages: Array.from({ length: 7 }, (_, i) => ({
        title: `Page ${i + 1}`,
        url: `https://acme.com/p${i + 1}`,
        description: '',
      })),
    }
    const out = generateLlmsTxt(manyPages)
    expect(out).toContain('## Optional')
    // Homepage + 5 primary live under Key Pages; the 6th & 7th go to Optional.
    expect(out).toContain('- [Page 6](https://acme.com/p6)')
  })

  it('always has at least a Key Pages section with the homepage', () => {
    const minimal: LlmsInput = { brandName: 'Bare', domain: 'bare.io' }
    const out = generateLlmsTxt(minimal)
    expect(out).toContain('# Bare')
    expect(out).toContain('## Key Pages')
    expect(out).toContain('- [Homepage](https://bare.io): Main website')
    expect(out).not.toContain('## Optional')
  })

  it('ends with trailing newline', () => {
    const out = generateLlmsTxt(baseInput)
    expect(out.endsWith('\n')).toBe(true)
  })
})

describe('generateLlmsFullTxt', () => {
  it('is strictly longer than the short variant', () => {
    const short = generateLlmsTxt(baseInput)
    const full = generateLlmsFullTxt(baseInput)
    expect(full.length).toBeGreaterThan(short.length)
  })

  it('includes Brand Identity section', () => {
    const out = generateLlmsFullTxt(baseInput)
    expect(out).toContain('## Brand Identity')
    expect(out).toContain('- **Official Name**: Acme Corp')
    expect(out).toContain('- **Also Known As**: Acme, AcmeCorp')
    expect(out).toContain('- **Website**: https://acme.com')
    expect(out).toContain('- **Industry**: Software')
  })

  it('renders products as H3 headings with body', () => {
    const out = generateLlmsFullTxt(baseInput)
    expect(out).toContain('### Acme Flow')
    expect(out).toContain('Visual workflow builder')
    expect(out).toContain('### Acme Connect')
  })

  it('includes FAQ section with H3 questions', () => {
    const out = generateLlmsFullTxt(baseInput)
    expect(out).toContain('## Frequently Asked Questions')
    expect(out).toContain('### What is Acme Flow?')
    expect(out).toContain('A visual automation builder')
  })

  it('includes Market Context with competitors', () => {
    const out = generateLlmsFullTxt(baseInput)
    expect(out).toContain('## Market Context')
    expect(out).toContain('Zapier, Make')
  })

  it('includes footer with AIO Pulse attribution and ISO date', () => {
    const out = generateLlmsFullTxt(baseInput)
    expect(out).toContain('Generated by AIO Pulse Advance')
    expect(out).toMatch(/\d{4}-\d{2}-\d{2}/)
  })
})
